import { CommonModule } from '@angular/common';
import { Component, OnDestroy, OnInit, computed, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ClarityModule } from '@clr/angular';
import { CarbonIcon } from '../../carbon-icon';
import { apiBase, hostFetch } from '../../api-base';
import { IdentityEngineInstallParameters, FoundationRegistryService } from '../../registry/foundation-registry.service';
import { PfsPluginTabId, PluginPageHeaderComponent, PluginPageHeaderModel, PluginPageTab, PluginTabsComponent, pfsPluginTabs } from '../../shared/plugin-page-shell.component';
import { ViewRouter } from '../../view-router';
import { KcService } from './identity.services';
import ArrowLeft16 from '@carbon/icons/es/arrow--left/16';
import ListBoxes16 from '@carbon/icons/es/list--boxes/16';
import Catalog16 from '@carbon/icons/es/catalog/16';
import DataAdd16 from '@carbon/icons/es/data--add/16';
import Settings16 from '@carbon/icons/es/settings/16';
import Renew16 from '@carbon/icons/es/renew/16';

type Tab = PfsPluginTabId;
type KeycloakForm = IdentityEngineInstallParameters;
interface PostgresInstanceOption { name: string; plan: string; provider: string; }

const LOGO = 'https://logos.opl.io.kr/i/keycloak';
const MANUAL_ID = 'keycloak-operations-ko';
const DEFAULT_FORM: KeycloakForm = {
  version: '26.0', profile: 'development', replicas: 1, resourceProfile: 'small',
  cpuRequest: '250m', memoryRequest: '512Mi', cpuLimit: '1', memoryLimit: '1536Mi',
  monitoring: false, ingressMode: 'cluster-internal', databaseMode: 'dedicated', databasePlan: 'postgresql-dev-single', databaseTargetClaim: '',
};

@Component({
  selector: 'app-keycloak',
  standalone: true,
  imports: [CommonModule, FormsModule, ClarityModule, CarbonIcon, PluginPageHeaderComponent, PluginTabsComponent],
  styles: [`
    :host{display:block;min-width:0}.kc-work{max-width:82rem}.kc-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:14px}.kc-panel{background:#fff;border:1px solid var(--os-border);padding:16px}.kc-panel h2{font-size:1rem;margin:0 0 8px}.kc-actions{display:flex;justify-content:flex-end;align-items:center;gap:12px}.kc-log{margin-top:12px;max-height:190px;overflow:auto;padding:12px;background:#161616;color:#f4f4f4;font-family:monospace}.kc-progress{height:6px;background:#e0e0e0;margin-top:10px}.kc-progress>div{height:100%;background:#4c6fff}.kc-once{padding:12px;border:1px solid #f1c21b;background:#fff8e1}.ok{color:#198038}.warn{color:#8e6a00}
    .kc-management-scope{display:flex;align-items:center;justify-content:space-between;gap:16px;padding:.55rem .75rem;background:#fff7f1;border-top:1px solid #f7c8aa;border-bottom:1px solid #f7c8aa;color:var(--os-text-sec);font-size:.72rem}.kc-management-scope b{color:#a33b00}.kc-navigation-row{border-top:0}.kc-runtime-context{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));margin-bottom:16px;border:1px solid var(--os-border);background:#fff}.kc-runtime-context>div{display:grid;gap:3px;min-height:4.8rem;padding:12px 16px;border-right:1px solid var(--os-border)}.kc-runtime-context>div:last-child{border-right:0}.kc-runtime-context span,.kc-runtime-context small{color:var(--os-muted);font-size:.68rem}.kc-runtime-context b{font-size:.9rem}.kc-bridge{display:grid;grid-template-columns:14rem 1fr 8rem;align-items:center;gap:18px;margin-bottom:16px;padding:12px 16px;border-top:1px solid #9bd8b0;border-bottom:1px solid #9bd8b0;background:#f3fbf6}.kc-bridge-title{display:grid;gap:3px}.kc-bridge-title span{color:#526eff;font-size:.66rem;font-weight:700;letter-spacing:.08em}.kc-bridge-title b{color:#198038}.kc-bridge ol{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:22px;margin:0;padding:0;list-style:none}.kc-bridge li{position:relative;display:grid;gap:2px}.kc-bridge li:not(:last-child)::after{content:'›';position:absolute;right:-14px;top:10px;color:#8d8d8d;font-size:1.5rem}.kc-bridge li span,.kc-bridge li small{color:var(--os-muted);font-size:.66rem}.kc-bridge-count{text-align:right}.kc-bridge-count b,.kc-bridge-count span{display:block}.kc-bridge-count span{color:var(--os-muted);font-size:.66rem}.kc-fleet-card{display:grid;grid-template-columns:auto 1fr auto;gap:16px;align-items:center;padding:18px;border:1px solid var(--os-border);background:#fff}.kc-fleet-logo{width:3rem;height:3rem;object-fit:contain}.kc-profile-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:14px}.kc-profile{display:grid;gap:10px;min-height:12rem;padding:18px;border:1px solid var(--os-border);background:#fff;text-align:left}.kc-profile.current{outline:2px solid var(--os-brand-500);outline-offset:-2px}.kc-profile h3,.kc-profile p{margin:0}.kc-profile p{color:var(--os-text-sec);font-size:.76rem;line-height:1.5}.kc-profile .btn{align-self:end;justify-self:start}
    @media(max-width:1180px){.kc-bridge{grid-template-columns:1fr}.kc-runtime-context,.kc-profile-grid{grid-template-columns:1fr 1fr}.kc-bridge-count{text-align:left}}
    @media(max-width:900px){.kc-grid,.kc-runtime-context,.kc-profile-grid{grid-template-columns:1fr}.kc-runtime-context>div{border-right:0;border-bottom:1px solid var(--os-border)}.kc-runtime-context>div:last-child{border-bottom:0}.kc-management-scope{align-items:flex-start;flex-direction:column}}
  `],
  template: `
    <a class="vl-back" (click)="back()" (keydown.enter)="back()" role="button" tabindex="0"><os-cicon [icon]="iBack" [size]="16" /> PFSS 모듈</a>
    <section class="pgp-page-frame" aria-label="Keycloak plugin 개요와 메뉴">
      <osp-plugin-page-header [model]="headerModel()" headingId="keycloak-plugin-title">
        <div pluginHeaderContext class="pgp-header-tools">
          <nav class="pgp-management-actions pgp-management-actions--header" aria-label="Keycloak 관리 작업">
            <a class="pgp-management-action" href="/pfss/keycloak/cluster" aria-label="전체 서비스" title="전체 서비스" [class.active]="tab()==='cluster'" [attr.aria-current]="tab()==='cluster'?'page':null"><os-cicon [icon]="iFleet" [size]="16" /><span>전체 서비스</span></a>
            <a class="pgp-management-action" href="/pfss/keycloak/config" aria-label="설정 카탈로그" title="설정 카탈로그" [class.active]="tab()==='config'" [attr.aria-current]="tab()==='config'?'page':null"><os-cicon [icon]="iCatalog" [size]="16" /><span>설정 카탈로그</span></a>
            <a class="pgp-management-action pgp-management-action--primary" href="/pfss/keycloak/claims" aria-label="Keycloak 생성" title="Keycloak 생성" [class.active]="tab()==='claims'" [attr.aria-current]="tab()==='claims'?'page':null"><os-cicon [icon]="iAdd" [size]="16" /><span>Keycloak 생성</span></a>
            <a class="pgp-management-action" href="/pfss/keycloak/operator" aria-label="엔진 관리" title="엔진 관리" [class.active]="tab()==='operator'" [attr.aria-current]="tab()==='operator'?'page':null"><os-cicon [icon]="iSettings" [size]="16" /><span>엔진 관리</span></a>
          </nav>
          <div class="pgp-header-context" aria-label="Keycloak 운영 컨텍스트">
            <div class="pgp-header-context-unit">
              <clr-select-container class="pgp-header-context-field">
                <label>Namespace</label>
                <select clrSelect name="keycloakNamespace" aria-label="Keycloak Namespace 선택" [ngModel]="svc.ns">
                  <option [ngValue]="svc.ns">{{svc.ns}}</option>
                </select>
              </clr-select-container>
              <button class="btn btn-sm btn-link pgp-header-context-action" type="button"
                aria-label="선택한 Namespace에 Keycloak 서비스 추가" title="Keycloak 서비스 추가" (click)="openTab('claims')">추가</button>
            </div>
            <div class="pgp-header-context-unit">
              <clr-select-container class="pgp-header-context-field" *ngIf="exists()">
                <label>Keycloak 서비스</label>
                <select clrSelect name="keycloakService" aria-label="Keycloak 서비스 선택" [ngModel]="svc.name" disabled>
                  <option [ngValue]="svc.name">{{svc.name}}</option>
                </select>
              </clr-select-container>
              <button class="btn btn-sm btn-link pgp-header-context-refresh" type="button" aria-label="Keycloak 컨텍스트 새로고침" title="새로고침" (click)="refresh()"><os-cicon [icon]="iRenew" [size]="16" /></button>
            </div>
          </div>
        </div>
      </osp-plugin-page-header>
      <div class="kc-navigation-row" *ngIf="exists()&&!isManagementView()"><osp-plugin-tabs [tabs]="tabsForUi()" [active]="tab()" ariaLabel="Keycloak 운영 메뉴" (selected)="openTab($event)" /></div>
      <div class="kc-management-scope" *ngIf="isManagementView()"><span><b>관리 워크스페이스</b> · 운영 상태 탭과 분리된 Keycloak 서비스·프로파일·프로비저닝 영역입니다.</span><button *ngIf="exists()" class="btn btn-sm btn-link" type="button" (click)="openOperational()">선택한 서비스로 돌아가기</button></div>
    </section>

    <ng-container *ngIf="tab()==='overview'">
      <section class="pgp-workspace pgp-workspace--full" aria-label="선택한 Namespace의 Keycloak">
      <div class="pgp-loading" *ngIf="svc.state()==='loading'">Keycloak 서비스와 FoundationModel 상태를 확인하고 있습니다.</div>
      <article class="pgp-empty-state" *ngIf="svc.state()!=='loading'&&!exists()"><div class="pgp-empty-copy"><span class="vl-eyebrow">{{svc.ns}}</span><h2>이 Namespace에는 Keycloak 서비스가 없습니다</h2><p>Keycloak 서비스를 생성하면 이 화면이 모니터링·토폴로지·Realm·보호 정책 운영 워크스페이스로 전환됩니다.</p></div><div class="os-actions"><button class="btn btn-primary" type="button" (click)="openTab('claims')">Keycloak 서비스 생성</button><span class="os-dim">Provisioning에서 검증된 프로파일과 버전을 선택합니다.</span></div></article>
      <ng-container *ngIf="exists()">
      <section class="kc-runtime-context" aria-label="선택한 Keycloak 운영 대상"><div><span>운영 대상</span><b>{{svc.name}}</b><small>{{svc.ns}}</small></div><div><span>수명주기</span><b [class.ok]="svc.ready()">{{svc.phase()}}</b><small>{{svc.readyN()}} / {{svc.totalN()}} replicas ready</small></div><div><span>운영 계약</span><b>{{form().profile}}</b><small>설정·생성 작업은 상단 관리 메뉴에서 수행합니다.</small></div></section>
      <section class="kc-bridge" aria-label="Keycloak 프로비저닝 연결 상태"><div class="kc-bridge-title"><span>PROVISIONING BRIDGE</span><b>{{controlPlaneReady()?'Connected':'Reconciling'}}</b></div><ol><li><span>요청</span><strong>IdentityServiceClaim</strong></li><li><span>배정·수명주기</span><strong>Foundation Control Plane</strong><small>FoundationModel/identity</small></li><li><span>실행</span><strong>Keycloak</strong><small>Deployment</small></li></ol><div class="kc-bridge-count"><b>{{svc.readyN()}} / {{svc.totalN()}}</b><span>managed replicas ready</span></div></section>
      <div class="pgp-dashboard">
        <article class="pgp-panel"><h2>Package readiness</h2><p>설치 수명주기의 실제 상태만 표시합니다.</p><div class="pgp-status-list"><div><span>PFS Control Plane</span><b [class.ok]="controlPlaneReady()">{{controlPlaneReady()?'Ready':'Required'}}</b></div><div><span>FoundationModel/identity</span><b>{{modelState()}}</b></div><div><span>Keycloak Deployment</span><b [class.ok]="svc.ready()">{{svc.phase()}}</b></div><div><span>Managed replicas</span><b [class.ok]="svc.ready()">{{svc.readyN()}} / {{svc.totalN()}}</b></div></div><button class="btn btn-sm btn-primary" (click)="openTab('operator')">Operator 확인</button></article>
        <article class="pgp-panel"><h2>Service health</h2><p>Deployment와 Pod가 보고한 실제 가용성입니다.</p><div class="pgp-health"><strong>{{availability()}}%</strong><span>replicas ready</span><progress [value]="svc.readyN()" [max]="svc.totalN()||1" aria-label="Keycloak replica 가용성"></progress></div><dl class="os-kv"><dt>Issuer</dt><dd class="os-mono">{{svc.issuer()}}</dd><dt>Image</dt><dd class="os-mono">{{svc.image()||'—'}}</dd><dt>Restarts</dt><dd>{{svc.restarts()}}</dd></dl></article>
        <article class="pgp-panel"><h2>Operations policy</h2><p>선언된 신원 서비스의 보호·접근 경계입니다.</p><div class="pgp-policy-grid"><div><span>Registration</span><b>Disabled</b></div><div><span>Direct grants</span><b>Disabled</b></div><div><span>PKCE</span><b class="ok">S256</b></div><div><span>Ingress</span><b>{{form().ingressMode}}</b></div><div><span>Database</span><b class="ok">Managed PostgreSQL</b></div><div><span>Monitoring</span><b>{{form().monitoring?'Enabled':'Pending'}}</b></div></div></article>
      </div>
      <section class="pgp-description"><div><h2>Description</h2><p>Keycloak plugin은 Console 인증용 Kanidm과 분리된 workforce IAM입니다. FoundationModel/identity 선언으로 OIDC realm, workload, 소비 계약과 보안 경계를 운영합니다.</p></div><div><h2>Documentation</h2><a [href]="manualUrl">OpenSphere Keycloak 설치·운영 안내서 (한글)</a><a href="https://www.keycloak.org/documentation" target="_blank" rel="noreferrer">Keycloak 공식 문서</a><button class="btn btn-sm btn-link" type="button" (click)="openTab('documentation')">문서 등록 계약 보기</button></div></section>
      </ng-container>
      </section>
    </ng-container>

    <section class="pgp-workspace" *ngIf="tab()==='operator'">
      <div class="pgp-section-head"><div><span class="vl-eyebrow">Internal dependency</span><h2>Foundation Control Plane</h2></div><span class="label" [ngClass]="controlPlaneReady()?'label-success':'label-warning'">{{controlPlaneReady()?'Ready':'Required'}}</span></div>
      <clr-alert clrAlertType="info" [clrAlertClosable]="false"><clr-alert-item><span class="alert-text">Keycloak은 FoundationModel/identity 선언을 foundation-control-plane이 SSA로 적용합니다. 별도 Operator는 없습니다.</span></clr-alert-item></clr-alert>
      <dl class="os-kv"><dt>Desired-state owner</dt><dd class="os-mono">FoundationModel/identity</dd><dt>Managed workload</dt><dd class="os-mono">Deployment/foundation-identity-keycloak</dd><dt>Database allocation</dt><dd>{{form().databaseMode==='dedicated'?'새 전용 인스턴스':'기존 인스턴스에 전용 DB'}}</dd><dt>Realm import</dt><dd class="os-mono">opensphere-workforce</dd><dt>Image source</dt><dd class="os-mono">ghcr.io/opensphere-platform/mirror/keycloak</dd></dl>
    </section>

    <section class="pgp-workspace pgp-workspace--full" *ngIf="tab()==='cluster'">
      <div class="pgp-section-head"><div><span class="vl-eyebrow">Managed services</span><h2>Keycloak Service Fleet</h2><p>Foundation Control Plane이 관리하는 Keycloak 서비스를 Namespace 기준으로 확인합니다.</p></div><button class="btn btn-sm" type="button" (click)="refresh()">새로고침</button></div>
      <article class="kc-fleet-card" *ngIf="exists(); else emptyFleet"><img class="kc-fleet-logo" [src]="logoUrl" alt=""/><div><h3>{{svc.name}}</h3><dl class="os-kv"><dt>Lifecycle</dt><dd>{{svc.phase()}}</dd><dt>Namespace</dt><dd class="os-mono">{{svc.ns}}</dd><dt>Endpoint</dt><dd class="os-mono">{{svc.http}}</dd><dt>Profile</dt><dd>{{form().profile}}</dd></dl></div><button class="btn btn-primary" type="button" (click)="openOperational()">운영 워크스페이스</button></article>
      <ng-template #emptyFleet><article class="pgp-empty-state"><div class="pgp-empty-copy"><span class="vl-eyebrow">{{svc.ns}}</span><h2>관리 중인 Keycloak 서비스가 없습니다</h2><p>서비스를 생성하면 Fleet에 등록되고 운영 워크스페이스가 활성화됩니다.</p></div><div class="os-actions"><button class="btn btn-primary" type="button" (click)="openTab('claims')">Keycloak 서비스 생성</button></div></article></ng-template>
    </section>

    <section class="pgp-workspace pgp-workspace--full" *ngIf="tab()==='config'">
      <div class="pgp-section-head"><div><span class="vl-eyebrow">Reusable configuration</span><h2>Profile Catalog</h2><p>검증된 버전·자원·데이터 내구성 정책을 서비스 생성에 재사용합니다.</p></div></div>
      <div class="kc-profile-grid">
        <article class="kc-profile" [class.current]="form().profile==='development'"><span class="label label-success">Available</span><h3>Development</h3><p>Keycloak 26.0 · replica 1 · 전용 PostgreSQL. 개발·검증용 내구성 프로파일입니다.</p><dl class="os-kv"><dt>Resources</dt><dd>Small</dd><dt>Database plan</dt><dd>postgresql-dev-single</dd><dt>Data protection</dt><dd>Retain</dd></dl><button class="btn btn-sm btn-primary" type="button" (click)="chooseProfile('development')">선택 후 생성</button></article>
        <article class="kc-profile" [class.current]="form().profile==='production'"><span class="label label-success">Available</span><h3>Production</h3><p>다중 Keycloak replica와 HA·PITR PostgreSQL을 함께 선언하는 운영 프로파일입니다.</p><dl class="os-kv"><dt>Resources</dt><dd>Large</dd><dt>Database plan</dt><dd>postgresql-prod-ha-pitr</dd><dt>Data protection</dt><dd>HA · PITR</dd></dl><button class="btn btn-sm btn-primary" type="button" (click)="chooseProfile('production')">선택 후 생성</button></article>
        <article class="kc-profile" [class.current]="form().profile==='custom'"><span class="label">Configurable</span><h3>Custom</h3><p>Keycloak 자원과 검증된 PostgreSQL PFSS 플랜을 직접 조합합니다.</p><dl class="os-kv"><dt>Version</dt><dd>26.0</dd><dt>Replica limit</dt><dd>1–5</dd><dt>Database</dt><dd>Managed PostgreSQL</dd></dl><button class="btn btn-sm btn-primary" type="button" (click)="chooseProfile('custom')">선택 후 생성</button></article>
      </div>
    </section>

    <section class="pgp-workspace pgp-workspace--full" *ngIf="tab()==='claims'">
      <div class="pgp-section-head"><div><span class="vl-eyebrow">Provisioning</span><h2>Keycloak 서비스 생성</h2><p>{{svc.ns}} Namespace에 FoundationModel/identity 선언을 제출합니다.</p></div><span class="label" [ngClass]="exists()?'label-success':'label-warning'">{{exists()?'Managed':'Not created'}}</span></div>
      <section class="pgp-steps" aria-label="Keycloak 서비스 생성 단계"><div class="pgp-step done"><span class="pgp-step-n">1</span><span><b>Operator</b><small>Foundation Control Plane</small></span></div><div class="pgp-step current"><span class="pgp-step-n">2</span><span><b>Profile</b><small>Version · Resources · Access</small></span></div><div class="pgp-step"><span class="pgp-step-n">3</span><span><b>검토·생성</b><small>FoundationModel/identity</small></span></div></section>
      <form class="pgp-form" (ngSubmit)="apply()">
        <fieldset [disabled]="applying()"><legend>Version & profile</legend><div class="pgp-form-grid">
          <label><span>운영 프로파일</span><select name="profile" [ngModel]="form().profile" (ngModelChange)="setProfile($event)"><option value="development">Development</option><option value="production">Production</option><option value="custom">Custom</option></select><small>프로파일은 Keycloak 자원과 PostgreSQL 플랜의 기본 조합을 선택합니다.</small></label>
          <label><span>Keycloak image tag</span><select name="version" [ngModel]="form().version" (ngModelChange)="patch({version:$event})"><option value="26.0">26.0 · mirrored stable</option></select><small>검증·미러링된 태그만 선택할 수 있습니다.</small></label>
          <label><span>Replicas</span><input name="replicas" type="number" min="1" max="5" [ngModel]="form().replicas" (ngModelChange)="patch({replicas:+$event,profile:'custom'})"/><small>선택한 운영 프로파일에 맞춰 1–5개 replica를 선언합니다.</small></label>
          <label><span>Resource profile</span><select name="resourceProfile" [ngModel]="form().resourceProfile" (ngModelChange)="setResourceProfile($event)"><option value="small">Small</option><option value="medium">Medium</option><option value="large">Large</option></select></label>
        </div></fieldset>
        <fieldset [disabled]="applying()"><legend>Database</legend><div class="pgp-form-grid">
          <label><span>데이터베이스 배정</span><select name="databaseMode" [ngModel]="form().databaseMode" (ngModelChange)="setDatabaseMode($event)" [disabled]="exists()"><option value="dedicated">새 PostgreSQL 인스턴스 생성</option><option value="existing-instance">기존 인스턴스에 DB 추가</option></select><small>{{exists()?'설치 후 배정 방식은 변경할 수 없습니다.':'인스턴스 수명주기와 Keycloak DB 배정을 선택합니다.'}}</small></label>
          <label *ngIf="form().databaseMode==='dedicated'"><span>PostgreSQL PFSS 플랜</span><select name="databasePlan" [ngModel]="form().databasePlan" (ngModelChange)="patch({databasePlan:$event,profile:'custom'})"><option value="postgresql-dev-single">Development · single · 10Gi</option><option value="postgresql-compact-2">Compact · 2 instances · 20Gi</option><option value="postgresql-prod-ha-pitr">Production · 3 instances · HA/PITR</option></select><small>Keycloak 전용 PostgreSQL 인스턴스와 DB를 생성합니다.</small></label>
          <label *ngIf="form().databaseMode==='existing-instance'"><span>기존 PostgreSQL 인스턴스</span><select name="databaseTargetClaim" [ngModel]="form().databaseTargetClaim" (ngModelChange)="setDatabaseTarget($event)" [disabled]="exists()||postgresCatalogState()!=='ok'"><option value="">선택하세요</option><option *ngFor="let pg of postgresInstances()" [value]="pg.name">{{pg.name}} · {{pg.plan}}</option></select><small *ngIf="postgresCatalogState()==='loading'">Ready 인스턴스를 조회하고 있습니다.</small><small *ngIf="postgresCatalogState()==='error'">PostgreSQL PFSS 인스턴스 조회에 실패했습니다.</small><small *ngIf="postgresCatalogState()==='ok'&&!postgresInstances().length">사용 가능한 Ready 인스턴스가 없습니다.</small><small *ngIf="selectedPostgresInstance() as pg">{{pg.provider}} · Keycloak 전용 DB와 Owner 계정을 추가합니다.</small></label>
          <label><span>Database</span><input value="keycloak" disabled/><small>Keycloak 전용 database를 bootstrap합니다.</small></label>
          <label><span>PostgresClaim</span><input value="foundation-identity-keycloak-pg" disabled/><small>PostgreSQL PFSS가 수명주기를 관리합니다.</small></label>
          <label><span>Credential binding</span><input [value]="form().databaseMode==='dedicated'?'pgc-foundation-identity-keycloak-pg-binding':'Ready 후 status.bindingRef 자동 발급'" disabled/><small>계정 정보는 SecretRef로만 Keycloak에 전달됩니다.</small></label>
        </div></fieldset>
        <fieldset [disabled]="applying()"><legend>Resources & access</legend><div class="pgp-form-grid">
          <label><span>CPU request</span><input name="cpuRequest" [ngModel]="form().cpuRequest" (ngModelChange)="patch({cpuRequest:$event})"/></label><label><span>Memory request</span><input name="memoryRequest" [ngModel]="form().memoryRequest" (ngModelChange)="patch({memoryRequest:$event})"/></label><label><span>CPU limit</span><input name="cpuLimit" [ngModel]="form().cpuLimit" (ngModelChange)="patch({cpuLimit:$event})"/></label><label><span>Memory limit</span><input name="memoryLimit" [ngModel]="form().memoryLimit" (ngModelChange)="patch({memoryLimit:$event})"/></label>
          <label><span>접근 정책</span><select name="ingressMode" [ngModel]="form().ingressMode" (ngModelChange)="patch({ingressMode:$event})"><option value="cluster-internal">Cluster internal</option><option value="private-ingress" disabled>Private ingress · OIDC/TLS connector pending</option></select></label>
        </div></fieldset>
        <clr-alert *ngIf="validationError()" clrAlertType="danger" [clrAlertClosable]="false"><clr-alert-item><span class="alert-text">{{validationError()}}</span></clr-alert-item></clr-alert>
        <div class="kc-actions"><span class="os-dim">{{form().databaseMode==='dedicated'?'FoundationModel/identity → 새 PostgresClaim · SGCluster':'FoundationModel/identity → SharedDatabase · '+(form().databaseTargetClaim||'인스턴스 선택')}} → Keycloak Deployment</span><button class="btn btn-primary" type="submit" [disabled]="!canApply()">{{exists()?'운영 구성 적용':'Keycloak 설치'}}</button></div>
        <div class="kc-progress" *ngIf="applying()"><div [style.width.%]="progress()"></div></div><div class="kc-log" *ngIf="logs().length"><div *ngFor="let line of logs()">{{line}}</div></div>
      </form>
    </section>

    <section class="pgp-workspace" *ngIf="tab()==='topology'"><div class="pgp-section-head"><div><span class="vl-eyebrow">Runtime</span><h2>Topology</h2></div><button class="btn btn-sm" (click)="refresh()">새로고침</button></div><clr-alert *ngIf="svc.state()==='loading'" clrAlertType="info" [clrAlertClosable]="false"><clr-alert-item><span class="alert-text">Keycloak Deployment와 Pod 상태를 확인하고 있습니다.</span></clr-alert-item></clr-alert><clr-alert *ngIf="svc.state()==='noperm'" clrAlertType="warning" [clrAlertClosable]="false"><clr-alert-item><span class="alert-text">현재 사용자에게 Keycloak workload 조회 권한이 없습니다. Foundation 권한 프로파일을 확인하세요.</span></clr-alert-item></clr-alert><clr-alert *ngIf="svc.state()==='nocrd'" clrAlertType="info" [clrAlertClosable]="false"><clr-alert-item><span class="alert-text">Keycloak workload가 아직 설치되지 않았습니다.</span><div class="alert-actions"><button class="btn alert-action" (click)="openTab('claims')">Provisioning</button></div></clr-alert-item></clr-alert><clr-alert *ngIf="svc.state()==='error'" clrAlertType="danger" [clrAlertClosable]="false"><clr-alert-item><span class="alert-text">Keycloak 런타임 상태 조회에 실패했습니다. API 경로와 control-plane 상태를 확인하세요.</span></clr-alert-item></clr-alert><div class="kc-grid"><article class="kc-panel"><h2>Deployment</h2><dl class="os-kv"><dt>Name</dt><dd class="os-mono">{{svc.name}}</dd><dt>Ready</dt><dd>{{svc.readyN()}}/{{svc.totalN()}}</dd><dt>Image</dt><dd class="os-mono">{{svc.image()||'—'}}</dd></dl></article><article class="kc-panel"><h2>Pod</h2><dl class="os-kv"><dt>Node</dt><dd class="os-mono">{{svc.node()}}</dd><dt>Restarts</dt><dd>{{svc.restarts()}}</dd><dt>Phase</dt><dd>{{svc.phase()}}</dd></dl></article><article class="kc-panel"><h2>Service</h2><dl class="os-kv"><dt>Endpoint</dt><dd class="os-mono">{{svc.http}}</dd><dt>Port</dt><dd>8080/TCP</dd><dt>Exposure</dt><dd>ClusterIP</dd></dl></article></div></section>

    <section class="pgp-workspace" *ngIf="tab()==='monitoring'"><div class="pgp-section-head"><div><span class="vl-eyebrow">Runtime signals</span><h2>Monitoring</h2></div><button class="btn btn-sm" (click)="refresh()">새로고침</button></div><div class="kc-grid"><article class="kc-panel"><h2>Availability</h2><strong>{{svc.readyN()}} / {{svc.totalN()}} Ready</strong></article><article class="kc-panel"><h2>Restarts</h2><strong>{{svc.restarts()}}</strong></article><article class="kc-panel"><h2>Phase</h2><strong>{{svc.phase()}}</strong></article></div></section>
    <section class="pgp-workspace" *ngIf="tab()==='domain'"><div class="pgp-section-head"><div><span class="vl-eyebrow">Identity domain</span><h2>Realms & Roles</h2></div></div><div class="kc-grid"><article class="kc-panel"><h2>OIDC issuer</h2><dl class="os-kv"><dt>Issuer</dt><dd class="os-mono">{{svc.issuer()}}</dd><dt>JWKS</dt><dd class="os-mono">{{svc.jwks()}}</dd><dt>Client flow</dt><dd>Authorization Code + PKCE S256</dd></dl></article><article class="kc-panel"><h2>Directory federation</h2><dl class="os-kv"><dt>Provider</dt><dd>Samba-AD</dd><dt>Protocol</dt><dd>LDAP :389</dd><dt>Status</dt><dd class="warn">Configuration managed in Keycloak Admin UI</dd></dl></article><article class="kc-panel"><h2>Provisioning authority</h2><p>사용자 프로비저닝 권위는 Syncope(IGA)입니다. JIT 사용자 생성은 허용하지 않습니다.</p></article></div><h3>소비 계약</h3><table class="table"><thead><tr><th>Claim</th><th>Endpoint</th><th>Authority</th></tr></thead><tbody><tr><td>OIDCClientClaim</td><td class="os-mono">{{svc.issuer()}}</td><td>Foundation Control Plane</td></tr><tr><td>DirectoryFederationBinding</td><td>LDAP :389</td><td>Samba-AD</td></tr><tr><td>IdentityProvisioningClaim</td><td>SCIM 2.0</td><td>Syncope IGA</td></tr></tbody></table></section>

    <section class="pgp-workspace" *ngIf="tab()==='backups'"><div class="pgp-section-head"><div><span class="vl-eyebrow">Protection policy</span><h2>Backups</h2></div></div><clr-alert clrAlertType="info" [clrAlertClosable]="false"><clr-alert-item><span class="alert-text">Keycloak 상태는 PostgreSQL PFSS가 배정한 전용 database에 저장됩니다. 백업·PITR은 새 인스턴스 플랜 또는 선택한 기존 인스턴스의 데이터 보호 계약을 따릅니다.</span></clr-alert-item></clr-alert><div class="kc-grid"><article class="kc-panel"><h2>Realm policy</h2><dl class="os-kv"><dt>Self registration</dt><dd>Disabled</dd><dt>Direct grants</dt><dd>Disabled</dd><dt>Identity providers</dt><dd>None</dd></dl></article><article class="kc-panel"><h2>Container security</h2><dl class="os-kv"><dt>Service account token</dt><dd>Not mounted</dd><dt>Privilege escalation</dt><dd>Denied</dd><dt>Capabilities</dt><dd>ALL dropped</dd></dl></article><article class="kc-panel"><h2>Data protection</h2><dl class="os-kv"><dt>Allocation</dt><dd>{{form().databaseMode==='dedicated'?'New instance':'Existing instance'}}</dd><dt>Plan</dt><dd>{{effectiveDatabasePlan()}}</dd><dt>Credential</dt><dd>SecretRef only</dd><dt>Backup/PITR</dt><dd [class.ok]="effectiveDatabasePlan()==='postgresql-prod-ha-pitr'">{{effectiveDatabasePlan()==='postgresql-prod-ha-pitr'?'Enabled':'Plan not enabled'}}</dd></dl></article></div></section>

    <section class="pgp-workspace" *ngIf="tab()==='events'"><div class="pgp-section-head"><div><span class="vl-eyebrow">Kubernetes signals</span><h2>Events</h2></div><button class="btn btn-sm" (click)="refresh()">새로고침</button></div><table class="table" *ngIf="svc.events().length; else noEvents"><thead><tr><th>Type</th><th>Reason</th><th>Message</th><th>Time</th></tr></thead><tbody><tr *ngFor="let e of svc.events()"><td>{{e.type}}</td><td>{{e.reason}}</td><td>{{e.message}}</td><td>{{e.lastTimestamp||e.eventTime||'—'}}</td></tr></tbody></table><ng-template #noEvents><p class="os-dim">최근 Keycloak 이벤트가 없습니다.</p></ng-template></section>

    <section class="pgp-workspace" *ngIf="tab()==='upgrade'">
      <div class="pgp-section-head"><div><span class="vl-eyebrow">Controlled lifecycle</span><h2>Upgrade & rollback</h2></div><span class="label label-warning">Production gate</span></div>
      <clr-alert clrAlertType="warning" [clrAlertClosable]="false"><clr-alert-item><span class="alert-text">업그레이드 전에는 Keycloak schema 호환성과 PostgreSQL 복구 지점을 함께 검증해야 합니다. 데이터베이스 플랜 변경은 별도 검토·적용 작업으로 처리합니다.</span></clr-alert-item></clr-alert>
      <dl class="os-kv"><dt>현재 선택</dt><dd>Keycloak {{form().version}}</dd><dt>Database plan</dt><dd>{{form().databasePlan}}</dd><dt>업그레이드 단위</dt><dd>image digest + realm schema + provider compatibility</dd><dt>Rollback 근거</dt><dd>realm export와 PostgreSQL 복구 시점</dd><dt>채널</dt><dd>서명 BOM의 stable / candidate / edge</dd></dl>
      <button class="btn btn-primary" type="button" (click)="openTab('config')">Profile Catalog 검토</button>
    </section>

    <section class="pgp-workspace" *ngIf="tab()==='documentation'">
      <div class="pgp-section-head"><div><span class="vl-eyebrow">Console Manual Registry</span><h2>Documentation</h2></div><span class="label label-success">자동 등록</span></div>
      <p>Foundation package 활성화 시 Keycloak 한글 설치·운영 안내서를 Console Manual Registry와 통합 검색에 등록합니다.</p>
      <dl class="os-kv"><dt>문서 ID</dt><dd class="os-mono">plugin:foundation/{{manualId}}</dd><dt>화면 경로</dt><dd class="os-mono">/pfss/keycloak</dd><dt>정본 수준</dt><dd>Tier 2 · 제품/운영 안내서</dd></dl>
      <a class="btn btn-sm btn-primary" [href]="manualUrl">한글 안내서 열기</a><a class="btn btn-sm" href="https://www.keycloak.org/documentation" target="_blank" rel="noreferrer">Keycloak 공식 문서</a>
    </section>
  `,
})
export class KeycloakComponent implements OnInit, OnDestroy {
  readonly svc = inject(KcService); private readonly reg = inject(FoundationRegistryService); private readonly vr = inject(ViewRouter);
  readonly iBack = ArrowLeft16; readonly iFleet = ListBoxes16; readonly iCatalog = Catalog16; readonly iAdd = DataAdd16; readonly iSettings = Settings16; readonly iRenew = Renew16; readonly logoUrl = LOGO; readonly manualId = MANUAL_ID; readonly manualUrl = `/manual?doc=${encodeURIComponent(`plugin:foundation/${MANUAL_ID}`)}`; readonly tab = signal<Tab>('overview'); readonly form = signal<KeycloakForm>({...DEFAULT_FORM}); readonly controlPlaneReady = signal(false); readonly postgresInstances = signal<PostgresInstanceOption[]>([]); readonly postgresCatalogState = signal<'loading'|'ok'|'error'>('loading'); readonly selectedPostgresInstance = computed(()=>this.postgresInstances().find(pg=>pg.name===this.form().databaseTargetClaim)); readonly applying = signal(false); readonly progress = signal(0); readonly logs = signal<string[]>([]);
  private timer: ReturnType<typeof setInterval>|undefined;
  readonly tabs: {id:Tab;label:string;runtime?:boolean}[]=pfsPluginTabs('Realms & Roles').map(tab=>({...tab,id:tab.id as Tab,runtime:['topology','events'].includes(tab.id)}));
  readonly validationError=computed(()=>{const f=this.form();if(f.version!=='26.0')return'검증된 Keycloak 26.0만 설치할 수 있습니다.';if(f.replicas<1||f.replicas>5)return'Replicas는 1–5 범위여야 합니다.';if(!['dedicated','existing-instance'].includes(f.databaseMode))return'PostgreSQL PFSS 데이터베이스 배정 방식을 선택해야 합니다.';if(f.databaseMode==='dedicated'&&!['postgresql-dev-single','postgresql-compact-2','postgresql-prod-ha-pitr'].includes(f.databasePlan))return'검증된 PostgreSQL PFSS 플랜을 선택해야 합니다.';if(f.databaseMode==='existing-instance'&&!f.databaseTargetClaim)return'Keycloak database를 추가할 기존 PostgreSQL 인스턴스를 선택해야 합니다.';if(f.databaseMode==='existing-instance'&&this.postgresCatalogState()==='ok'&&!this.selectedPostgresInstance())return'선택한 PostgreSQL 인스턴스가 Ready 상태가 아닙니다.';if(f.profile==='production'&&(this.effectiveDatabasePlan()!=='postgresql-prod-ha-pitr'||f.replicas<2))return'Production은 HA/PITR PostgreSQL 인스턴스와 Keycloak replica 2개 이상이 필요합니다.';return'';});
  readonly canApply=computed(()=>this.controlPlaneReady()&&!this.applying()&&!this.validationError());
  ngOnInit():void{const routeTab=location.pathname.split('/').filter(Boolean)[2] as Tab|undefined;this.vr.setModule('keycloak');const wanted=(routeTab||this.vr.tab()) as Tab;if(this.tabs.some(t=>t.id===wanted)||['operator','cluster','config','claims'].includes(wanted)){this.tab.set(wanted);this.vr.setTab(wanted);}void this.initialize();}
  ngOnDestroy():void{if(this.timer)clearInterval(this.timer);}
  private async initialize(){await Promise.allSettled([this.reg.refreshModels(),this.svc.refresh(),this.loadControlPlane(),this.loadPostgresInstances()]);const p=this.reg.parametersOf('keycloak') as any;const cfg=p?.identityEngines?.keycloak;if(cfg)this.form.update(f=>({...f,...cfg,databaseMode:cfg.databaseMode==='existing-instance'?'existing-instance':'dedicated',databaseTargetClaim:String(cfg.databaseTargetClaim||''),databasePlan:['postgresql-dev-single','postgresql-compact-2','postgresql-prod-ha-pitr'].includes(cfg.databasePlan)?cfg.databasePlan:'postgresql-dev-single'}));}
  exists(){return this.svc.state()==='ok'&&!!this.svc.deploy();} modelState(){return this.reg.modelOf('keycloak')||'확인 중';} availability(){return this.svc.totalN()?Math.round(this.svc.readyN()/this.svc.totalN()*100):0;}
  lifecycle(){if(!this.controlPlaneReady())return'Dependency required';if(!this.exists())return'Service required';return this.svc.ready()?'Ready':'Progressing';}
  headerModel():PluginPageHeaderModel{return{name:'Keycloak',logo:LOGO,stack:'PFSS',stackSeparator:'/',capability:'identity.iam.workspace',description:'Workforce IAM·SSO와 OIDC realm을 운영합니다.',lifecycle:this.lifecycle(),lifecycleClass:this.svc.ready()?'label-success':'label-warning',version:this.exists()?this.form().version:'—',profile:this.exists()?this.form().profile:'Not installed',managedFleet:true,managementActions:false};}
  tabsForUi():PluginPageTab[]{return this.tabs.map(t=>({id:t.id,label:t.label,disabled:!!t.runtime&&!this.exists(),badge:t.id==='events'?this.svc.events().filter((e:any)=>e.type==='Warning').length:''}));}
  isManagementView(){return['operator','cluster','config','claims'].includes(this.tab());} back(){this.vr.setModule('modules');} openTab(id:string){this.vr.setModule('keycloak');this.tab.set(id as Tab);this.vr.setTab(id);} openOperational(){this.openTab('overview');} patch(p:Partial<KeycloakForm>){this.form.update(f=>({...f,...p}));} effectiveDatabasePlan(){return this.form().databaseMode==='dedicated'?this.form().databasePlan:(this.selectedPostgresInstance()?.plan||'—');}
  chooseProfile(profile:KeycloakForm['profile']){this.setProfile(profile);this.openTab('claims');}
  setProfile(profile:KeycloakForm['profile']){const allocation=this.exists()?{databaseMode:this.form().databaseMode,databasePlan:this.form().databasePlan,databaseTargetClaim:this.form().databaseTargetClaim}:{};if(profile==='development'){this.form.set({...DEFAULT_FORM,...allocation});return;}if(profile==='production'){this.form.set({...DEFAULT_FORM,profile:'production',replicas:3,resourceProfile:'large',cpuRequest:'1',memoryRequest:'2Gi',cpuLimit:'4',memoryLimit:'4Gi',monitoring:true,databasePlan:'postgresql-prod-ha-pitr',...allocation});return;}this.patch({profile});}
  setResourceProfile(p:string){const x:any={small:{cpuRequest:'250m',memoryRequest:'512Mi',cpuLimit:'1',memoryLimit:'1536Mi'},medium:{cpuRequest:'500m',memoryRequest:'1Gi',cpuLimit:'2',memoryLimit:'2Gi'},large:{cpuRequest:'1',memoryRequest:'2Gi',cpuLimit:'4',memoryLimit:'4Gi'}};this.patch({resourceProfile:p,...(x[p]||{}),profile:'custom'});}
  setDatabaseMode(mode:KeycloakForm['databaseMode']){this.patch({databaseMode:mode,databaseTargetClaim:mode==='existing-instance'?(this.form().databaseTargetClaim||this.postgresInstances()[0]?.name||''):'',profile:'custom'});}
  setDatabaseTarget(name:string){const target=this.postgresInstances().find(pg=>pg.name===name);const plan=['postgresql-dev-single','postgresql-compact-2','postgresql-prod-ha-pitr'].includes(target?.plan||'')?target!.plan as KeycloakForm['databasePlan']:this.form().databasePlan;this.patch({databaseTargetClaim:name,databasePlan:plan,profile:'custom'});}
  async refresh(){await Promise.allSettled([this.svc.refresh(),this.reg.refreshModels(),this.loadControlPlane(),this.loadPostgresInstances()]);}
  private async loadPostgresInstances(){this.postgresCatalogState.set('loading');try{const r=await hostFetch(`${apiBase()}/api/k8s/apis/provisioning.opensphere.io/v1beta1/namespaces/${this.svc.ns}/postgresclaims`,{cache:'no-store'});if(!r.ok){this.postgresCatalogState.set('error');return;}const body=await r.json();const options:PostgresInstanceOption[]=(body?.items||[]).filter((item:any)=>item?.spec?.isolation==='Dedicated'&&item?.status?.phase==='Ready'&&item?.metadata?.name!=='foundation-identity-keycloak-pg').map((item:any)=>({name:String(item.metadata.name),plan:String(item?.spec?.planRef?.name||'custom'),provider:String(item?.status?.providerRef?.name||'StackGres')})).sort((a:PostgresInstanceOption,b:PostgresInstanceOption)=>a.name.localeCompare(b.name));this.postgresInstances.set(options);this.postgresCatalogState.set('ok');}catch{this.postgresCatalogState.set('error');}}
  private async loadControlPlane(){try{const r=await hostFetch(`${apiBase()}/api/k8s/apis/apps/v1/namespaces/opensphere-system/deployments/foundation-control-plane`,{cache:'no-store'});const b=r.ok?await r.json():null;this.controlPlaneReady.set(Number(b?.status?.readyReplicas||0)>0);}catch{this.controlPlaneReady.set(false);}}
  private log(m:string){this.logs.update(a=>[...a,`[${new Date().toLocaleTimeString()}] ${m}`]);}
  async apply(){if(!this.canApply())return;this.applying.set(true);this.progress.set(10);this.logs.set([]);this.log('FoundationModel/identity Keycloak 선언 제출');const ok=await this.reg.configureIdentityEngine('keycloak',this.form());if(!ok){this.log(`실패: ${this.reg.lastError()}`);this.progress.set(100);this.applying.set(false);return;}this.progress.set(35);this.log('선언 승인 · control-plane reconcile 관찰');let n=0;this.timer=setInterval(async()=>{n++;await this.svc.refresh();if(this.exists()){this.progress.set(Math.max(65,this.progress()));this.logOnce('deployment','Keycloak Deployment 생성 확인');}if(this.svc.ready()){this.progress.set(100);this.logOnce('ready','Keycloak Ready');this.applying.set(false);if(this.timer)clearInterval(this.timer);this.timer=undefined;}else if(n>=100){this.progress.set(100);this.log('5분 내 Ready 미도달 · Events 확인 필요');this.applying.set(false);if(this.timer)clearInterval(this.timer);this.timer=undefined;}},3000);}
  private logOnce(k:string,m:string){if(!this.logs().some(x=>x.includes(`[${k}]`)))this.log(`[${k}] ${m}`);}
}
