import { CommonModule } from '@angular/common';
import { Component, OnInit, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ClarityModule } from '@clr/angular';
import { PgAdminObject, PgAdminService, PgTypedAction } from './pg-admin.service';

type ActionId = PgTypedAction['action'];
interface DraftColumn { name: string; type: string; nullable: boolean; default: string }

@Component({
  selector: 'pg-admin',
  standalone: true,
  imports: [CommonModule, FormsModule, ClarityModule],
  styles: [`
    :host{display:block;min-width:0}.pga-head{display:flex;align-items:flex-end;justify-content:space-between;gap:1rem;margin-bottom:1rem}.pga-head h2{margin:.2rem 0;font-size:1.45rem}.pga-toolbar{display:flex;align-items:flex-end;gap:.7rem}.pga-toolbar label{min-width:15rem}.pga-toolbar select{width:100%}
    .pga-workbench{display:grid;grid-template-columns:minmax(15rem,22rem) minmax(30rem,1fr) minmax(16rem,22rem);min-height:34rem;border:1px solid var(--os-border);background:#fff}.pga-pane{min-width:0;border-right:1px solid var(--os-border)}.pga-pane:last-child{border-right:0}.pga-pane-head{min-height:3rem;padding:.75rem 1rem;border-bottom:1px solid var(--os-border);display:flex;align-items:center;justify-content:space-between}.pga-pane-head h3{font-size:1rem;margin:0}.pga-tree{height:30rem;overflow:auto;padding:.5rem 0}.pga-tree-section{border-bottom:1px solid #e8e8e8}.pga-tree-title{width:100%;border:0;background:transparent;text-align:left;padding:.62rem 1rem;font-weight:600}.pga-tree-item{width:100%;border:0;background:transparent;text-align:left;padding:.48rem 1rem .48rem 1.8rem;display:flex;justify-content:space-between;gap:.6rem}.pga-tree-item:hover,.pga-tree-item.active{background:#edf5ff}.pga-tree-item small{color:#697077}.pga-detail{padding:1rem;overflow:auto;max-height:30rem}.pga-summary{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:.65rem;margin-bottom:1rem}.pga-summary div{padding:.8rem;border-left:3px solid #4589ff;background:#f4f4f4}.pga-summary span{display:block;color:#525252;font-size:.75rem}.pga-summary strong{display:block;margin-top:.2rem}.pga-empty{padding:2rem;color:#6f6f6f;text-align:center}.pga-side{padding:1rem;overflow:auto;max-height:30rem}.pga-side h4{font-size:.9rem;margin:0 0 .5rem}.pga-side section{margin-bottom:1.25rem}.pga-pill-list{display:flex;flex-wrap:wrap;gap:.35rem}.pga-code{white-space:pre-wrap;word-break:break-word;background:#161616;color:#f4f4f4;padding:.8rem;font:12px/1.5 monospace}
    .pga-lower{display:grid;grid-template-columns:minmax(28rem,1fr) minmax(28rem,1fr);gap:1rem;margin-top:1rem}.pga-card{border:1px solid var(--os-border);background:#fff;padding:1rem}.pga-card h3{font-size:1.05rem;margin:0 0 .35rem}.pga-form-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:.75rem;margin-top:1rem}.pga-form-grid label,.pga-query label{display:flex;flex-direction:column;gap:.3rem}.pga-form-grid input,.pga-form-grid select{width:100%}.pga-columns{grid-column:1/-1;border-top:1px solid #e0e0e0;padding-top:.7rem}.pga-column{display:grid;grid-template-columns:1fr 1.25fr .8fr .5fr auto;gap:.45rem;align-items:end;margin-bottom:.45rem}.pga-reason{grid-column:1/-1}.pga-preview{grid-column:1/-1}.pga-actions{display:flex;justify-content:flex-end;align-items:center;gap:.75rem;margin-top:1rem}.pga-query textarea{width:100%;min-height:11rem;resize:vertical;font:13px/1.5 monospace}.pga-result{margin-top:1rem;max-height:18rem;overflow:auto}.pga-result table{margin-top:0}.pga-status-error{color:#da1e28}.pga-status-ok{color:#198038}.pga-risk{border-left:3px solid #f1c21b;padding:.55rem .75rem;background:#fff8e1}
    @media(max-width:1200px){.pga-workbench{grid-template-columns:17rem 1fr}.pga-pane-side{grid-column:1/-1;border-top:1px solid var(--os-border)}.pga-side{display:grid;grid-template-columns:repeat(3,1fr);gap:1rem}.pga-lower{grid-template-columns:1fr}}@media(max-width:760px){.pga-head{align-items:stretch;flex-direction:column}.pga-toolbar{align-items:stretch;flex-direction:column}.pga-toolbar label{min-width:0}.pga-workbench{display:block}.pga-pane{border-right:0;border-bottom:1px solid var(--os-border)}.pga-tree{height:18rem}.pga-summary{grid-template-columns:repeat(2,1fr)}.pga-side{display:block}.pga-lower{display:block}.pga-card{margin-bottom:1rem}.pga-form-grid{grid-template-columns:1fr}.pga-column{grid-template-columns:1fr}.pga-reason,.pga-columns,.pga-preview{grid-column:auto}}
  `],
  template: `
    <section class="pgp-workspace" aria-labelledby="postgres-admin-title">
      <div class="pga-head">
        <div><span class="vl-eyebrow">Live PostgreSQL catalog</span><h2 id="postgres-admin-title">Database Objects</h2><p class="os-dim">pgAdmin의 객체 계층을 OpenSphere 신원·MFA·감사 경계 안에서 제공합니다. 비밀번호와 DSN은 브라우저에 노출하지 않습니다.</p></div>
        <div class="pga-toolbar"><label><span>Database</span><select [ngModel]="svc.selectedDatabase()" (ngModelChange)="changeDatabase($event)"><option *ngFor="let db of svc.catalog()?.databases" [value]="db.name">{{db.name}}</option></select></label><button class="btn btn-sm" type="button" (click)="svc.refresh()" [disabled]="svc.state()==='loading'">새로고침</button></div>
      </div>
      <clr-alert *ngIf="svc.state()==='error'" clrAlertType="danger" [clrAlertClosable]="false"><clr-alert-item><span class="alert-text">{{svc.error()}}</span><div class="alert-actions"><button class="btn alert-action" (click)="svc.refresh()">다시 시도</button></div></clr-alert-item></clr-alert>
      <div class="pga-workbench" *ngIf="svc.catalog() as catalog">
        <aside class="pga-pane" aria-label="PostgreSQL object explorer">
          <div class="pga-pane-head"><h3>Object Explorer</h3><span class="label label-info">{{catalog.objects.length}}</span></div>
          <div class="pga-tree">
            <section class="pga-tree-section"><button class="pga-tree-title" type="button">Schemas</button><button *ngFor="let schema of catalog.schemas" class="pga-tree-item" [class.active]="svc.selectedSchema()===schema.name" (click)="selectSchema(schema.name)"><span>{{schema.name}}</span><small>{{schema.owner}}</small></button></section>
            <section class="pga-tree-section" *ngFor="let group of objectGroups()"><button class="pga-tree-title" type="button">{{group.label}} <span class="label">{{group.items.length}}</span></button><button *ngFor="let object of group.items" class="pga-tree-item" [class.active]="isSelected(object)" (click)="svc.selectedObject.set(object)"><span>{{object.name}}</span><small>{{formatBytes(object.size_bytes)}}</small></button></section>
            <section class="pga-tree-section"><button class="pga-tree-title" type="button">Functions <span class="label">{{functionsForSchema().length}}</span></button><button *ngFor="let fn of functionsForSchema()" class="pga-tree-item" type="button"><span>{{fn.name}}</span><small>{{fn.language}}</small></button></section>
          </div>
        </aside>
        <main class="pga-pane">
          <div class="pga-pane-head"><h3>{{svc.selectedObject()?.schema || svc.selectedSchema()}}<span *ngIf="svc.selectedObject()">.{{svc.selectedObject()?.name}}</span></h3><span class="label" *ngIf="svc.selectedObject()">{{svc.selectedObject()?.kind}}</span></div>
          <div class="pga-detail" *ngIf="svc.selectedObject() as object; else schemaSummary">
            <div class="pga-summary"><div><span>Kind</span><strong>{{object.kind}}</strong></div><div><span>Owner</span><strong>{{object.owner}}</strong></div><div><span>Estimated rows</span><strong>{{object.estimated_rows}}</strong></div><div><span>Total size</span><strong>{{formatBytes(object.size_bytes)}}</strong></div></div>
            <h4>Columns</h4><table class="table table-compact"><thead><tr><th>#</th><th>Name</th><th>Type</th><th>Nullable</th><th>Default</th></tr></thead><tbody><tr *ngFor="let column of svc.selectedColumns()"><td>{{column.ordinal_position}}</td><td class="os-mono">{{column.name}}</td><td>{{column.data_type}}{{column.data_type==='USER-DEFINED'?' · '+column.udt_name:''}}</td><td>{{column.nullable?'Yes':'No'}}</td><td class="os-mono">{{column.column_default||'—'}}</td></tr></tbody></table>
            <h4>Constraints</h4><table class="table table-compact"><thead><tr><th>Name</th><th>Kind</th><th>Definition</th></tr></thead><tbody><tr *ngFor="let item of svc.selectedConstraints()"><td class="os-mono">{{item.name}}</td><td>{{item.kind}}</td><td class="os-mono">{{item.definition}}</td></tr><tr *ngIf="!svc.selectedConstraints().length"><td colspan="3">No constraints</td></tr></tbody></table>
            <h4>Indexes / SQL</h4><div *ngFor="let item of svc.selectedIndexes()"><strong class="os-mono">{{item.name}}</strong><pre class="pga-code">{{item.definition}}</pre></div><p class="os-dim" *ngIf="!svc.selectedIndexes().length">No indexes</p>
          </div>
          <ng-template #schemaSummary><div class="pga-detail"><div class="pga-summary"><div><span>Schema</span><strong>{{svc.selectedSchema()}}</strong></div><div><span>Objects</span><strong>{{svc.visibleObjects().length}}</strong></div><div><span>Functions</span><strong>{{functionsForSchema().length}}</strong></div><div><span>Database</span><strong>{{catalog.selectedDatabase}}</strong></div></div><p class="pga-empty">왼쪽 Object Explorer에서 Table, View, Sequence를 선택하면 Columns·Constraints·Indexes·SQL 근거를 표시합니다.</p></div></ng-template>
        </main>
        <aside class="pga-pane pga-pane-side"><div class="pga-pane-head"><h3>Server context</h3></div><div class="pga-side"><section><h4>Extensions</h4><div class="pga-pill-list"><span class="label" *ngFor="let extension of catalog.extensions">{{extension.name}} {{extension.version}}</span><span *ngIf="!catalog.extensions.length">None</span></div></section><section><h4>Roles</h4><table class="table table-compact"><tbody><tr *ngFor="let role of catalog.roles"><td class="os-mono">{{role.name}}</td><td><span class="label" [ngClass]="role.superuser?'label-danger':role.login?'label-info':''">{{role.superuser?'superuser':role.login?'login':'group'}}</span></td></tr></tbody></table></section><section><h4>Sessions</h4><table class="table table-compact"><tbody><tr *ngFor="let item of catalog.activity"><td>{{item.database||'shared'}}</td><td>{{item.state}}</td><td>{{item.sessions}}</td></tr></tbody></table></section></div></aside>
      </div>

      <div class="pga-lower" *ngIf="svc.catalog()">
        <section class="pga-card"><h3>Object management</h3><p class="os-dim">직접 DDL 문자열 대신 검증된 action을 실행합니다. 모든 변경은 최근 MFA, 작업 사유와 Console durable audit가 필요합니다.</p><div class="pga-form-grid">
          <label><span>Action</span><select [(ngModel)]="action"><option value="create-schema">Create schema</option><option value="create-table">Create table</option><option value="create-index">Create index</option><option value="drop-index">Drop index</option><option value="drop-table">Drop table</option><option value="drop-schema">Drop schema</option></select></label>
          <label><span>Schema</span><input [(ngModel)]="draftSchema" placeholder="public" /></label>
          <label *ngIf="action!=='create-schema'&&action!=='drop-schema'"><span>{{action.includes('index')?'Index':'Table'}} name</span><input [(ngModel)]="draftName" /></label>
          <label *ngIf="action==='create-index'"><span>Table</span><input [(ngModel)]="draftTable" /></label>
          <label *ngIf="action==='create-index'"><span>Index columns</span><input [(ngModel)]="draftIndexColumns" placeholder="created_at, id" /></label>
          <label *ngIf="action==='create-index'"><span>Unique</span><select [(ngModel)]="draftUnique"><option [ngValue]="false">No</option><option [ngValue]="true">Yes</option></select></label>
          <div class="pga-columns" *ngIf="action==='create-table'"><div class="pga-column" *ngFor="let column of draftColumns(); let i=index"><label><span>Column</span><input [(ngModel)]="column.name" /></label><label><span>Type</span><select [(ngModel)]="column.type"><option *ngFor="let type of columnTypes" [value]="type">{{type}}</option></select></label><label><span>Default</span><select [(ngModel)]="column.default"><option value="">None</option><option value="now()">now()</option><option value="gen_random_uuid()">gen_random_uuid()</option><option value="true">true</option><option value="false">false</option></select></label><label><span>Nullable</span><input type="checkbox" [(ngModel)]="column.nullable" /></label><button class="btn btn-sm" type="button" (click)="removeColumn(i)" [disabled]="draftColumns().length===1">제거</button></div><button class="btn btn-sm" type="button" (click)="addColumn()" [disabled]="draftColumns().length>=32">Column 추가</button></div>
          <label class="pga-reason"><span>작업 사유</span><input [(ngModel)]="reason" maxlength="500" placeholder="8자 이상 변경 사유" /></label>
          <div class="pga-preview"><span>SQL preview</span><pre class="pga-code">{{sqlPreview()}}</pre></div>
        </div><div class="pga-risk" *ngIf="action.startsWith('drop-')">DROP은 RESTRICT로만 실행합니다. 의존 객체가 있으면 서버가 변경 없이 거부합니다.</div><div class="pga-actions"><span [class.pga-status-ok]="svc.actionState()==='done'" [class.pga-status-error]="svc.actionState()==='error'">{{svc.actionResult()}}</span><button class="btn" [class.btn-danger]="action.startsWith('drop-')" [class.btn-primary]="!action.startsWith('drop-')" type="button" (click)="runAction()" [disabled]="!actionReady()||svc.actionState()==='running'">{{svc.actionState()==='running'?'실행 중…':'검토 후 실행'}}</button></div></section>
        <section class="pga-card pga-query"><h3>Read-only Query Tool</h3><p class="os-dim">SELECT·WITH·EXPLAIN·SHOW·VALUES만 허용하며 server-side read-only transaction, 10초 timeout, 화면 500행 제한을 적용합니다.</p><label><span>SQL</span><textarea [(ngModel)]="querySql" spellcheck="false"></textarea></label><div class="pga-actions"><span class="pga-status-error">{{svc.queryError()}}</span><button class="btn btn-primary" type="button" (click)="svc.runQuery(querySql)" [disabled]="!querySql.trim()||svc.queryState()==='running'">{{svc.queryState()==='running'?'실행 중…':'Query 실행'}}</button></div><div class="pga-result" *ngIf="svc.queryResult() as result"><p>{{result.command}} · {{result.rowCount}} rows · {{result.durationMs}}ms <span class="label label-warning" *ngIf="result.truncated">500행까지만 표시</span></p><table class="table table-compact"><thead><tr><th *ngFor="let field of result.fields">{{field.name}}</th></tr></thead><tbody><tr *ngFor="let row of result.rows"><td *ngFor="let field of result.fields">{{cell(row,field.name)}}</td></tr></tbody></table></div></section>
      </div>
    </section>
  `,
})
export class PgAdminTab implements OnInit {
  readonly svc = inject(PgAdminService);
  readonly columnTypes = ['bigint', 'bigserial', 'boolean', 'bytea', 'date', 'double precision', 'integer', 'json', 'jsonb', 'numeric', 'real', 'smallint', 'text', 'time', 'timestamp', 'timestamp with time zone', 'uuid', 'varchar(255)'];
  readonly draftColumns = signal<DraftColumn[]>([{ name: 'id', type: 'bigserial', nullable: false, default: '' }]);
  action: ActionId = 'create-table'; draftSchema = 'public'; draftName = ''; draftTable = ''; draftIndexColumns = ''; draftUnique = false; reason = ''; querySql = 'SELECT current_database(), current_user, version();';
  ngOnInit(): void { if (!this.svc.catalog()) void this.svc.refresh(); }
  changeDatabase(database: string): void { this.svc.selectedDatabase.set(database); this.svc.selectedObject.set(null); void this.svc.refresh(database); }
  selectSchema(schema: string): void { this.svc.selectedSchema.set(schema); this.svc.selectedObject.set(null); this.draftSchema = schema; }
  objectGroups() { const objects = this.svc.visibleObjects(); const groups = [['Tables', ['table', 'partitioned table']], ['Views', ['view', 'materialized view']], ['Sequences', ['sequence']], ['Foreign tables', ['foreign table']]] as const; return groups.map(([label, kinds]) => ({ label, items: objects.filter((item) => (kinds as readonly string[]).includes(item.kind)) })).filter((group) => group.items.length); }
  functionsForSchema() { return (this.svc.catalog()?.functions ?? []).filter((item: any) => item.schema === this.svc.selectedSchema()); }
  isSelected(object: PgAdminObject) { const selected = this.svc.selectedObject(); return !!selected && selected.schema === object.schema && selected.name === object.name; }
  formatBytes(value: string | number) { const bytes = Number(value || 0); if (bytes >= 1024 ** 3) return `${(bytes / 1024 ** 3).toFixed(2)} GiB`; if (bytes >= 1024 ** 2) return `${(bytes / 1024 ** 2).toFixed(1)} MiB`; if (bytes >= 1024) return `${(bytes / 1024).toFixed(1)} KiB`; return `${bytes} B`; }
  cell(row: Record<string, unknown>, key: string) { const value = row[key]; if (value === null || value === undefined) return 'NULL'; return typeof value === 'object' ? JSON.stringify(value) : String(value); }
  addColumn() { this.draftColumns.update((items) => [...items, { name: '', type: 'text', nullable: true, default: '' }]); }
  removeColumn(index: number) { this.draftColumns.update((items) => items.filter((_, i) => i !== index)); }
  actionReady() { if (this.reason.trim().length < 8 || !this.draftSchema.trim()) return false; if (this.action === 'create-schema' || this.action === 'drop-schema') return true; if (!this.draftName.trim()) return false; if (this.action === 'create-table') return this.draftColumns().every((column) => column.name.trim() && column.type); if (this.action === 'create-index') return !!this.draftTable.trim() && !!this.draftIndexColumns.trim(); return true; }
  sqlPreview() { const s = this.draftSchema || 'public', n = this.draftName || '<name>'; if (this.action === 'create-schema') return `CREATE SCHEMA "${s}"`; if (this.action === 'drop-schema') return `DROP SCHEMA "${s}" RESTRICT`; if (this.action === 'drop-table') return `DROP TABLE "${s}"."${n}" RESTRICT`; if (this.action === 'drop-index') return `DROP INDEX "${s}"."${n}" RESTRICT`; if (this.action === 'create-index') return `CREATE${this.draftUnique ? ' UNIQUE' : ''} INDEX "${n}" ON "${s}"."${this.draftTable || '<table>'}" (${this.draftIndexColumns || '<columns>'})`; return `CREATE TABLE "${s}"."${n}" (${this.draftColumns().map((c) => `"${c.name || '<column>'}" ${c.type}${c.nullable ? '' : ' NOT NULL'}${c.default ? ' DEFAULT ' + c.default : ''}`).join(', ')})`; }
  async runAction() { const payload: PgTypedAction = { action: this.action, database: this.svc.selectedDatabase(), schema: this.draftSchema.trim(), name: this.draftName.trim() || undefined, table: this.draftTable.trim() || undefined, reason: this.reason.trim(), unique: this.draftUnique, columns: this.action === 'create-table' ? this.draftColumns().map((c) => ({ ...c, name: c.name.trim() })) : undefined, indexColumns: this.action === 'create-index' ? this.draftIndexColumns.split(',').map((x) => x.trim()).filter(Boolean) : undefined }; if (await this.svc.execute(payload)) this.reason = ''; }
}
