import { CommonModule } from '@angular/common';
import { Component, OnInit, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ClarityModule } from '@clr/angular';
import Add16 from '@carbon/icons/es/add/16';
import ChevronDown16 from '@carbon/icons/es/chevron--down/16';
import ChevronRight16 from '@carbon/icons/es/chevron--right/16';
import Code16 from '@carbon/icons/es/code/16';
import Db2Database16 from '@carbon/icons/es/db2--database/16';
import Document16 from '@carbon/icons/es/document/16';
import Folder16 from '@carbon/icons/es/folder/16';
import FolderOpen16 from '@carbon/icons/es/folder--open/16';
import Function16 from '@carbon/icons/es/function/16';
import Play16 from '@carbon/icons/es/play/16';
import Renew16 from '@carbon/icons/es/renew/16';
import Search16 from '@carbon/icons/es/search/16';
import ServerProxy16 from '@carbon/icons/es/server--proxy/16';
import Table16 from '@carbon/icons/es/table/16';
import TrashCan16 from '@carbon/icons/es/trash-can/16';
import { CarbonIcon } from '../../../carbon-icon';
import { PgAdminObject, PgAdminService, PgTypedAction } from './pg-admin.service';

type ActionId = PgTypedAction['action'];
type WorkspaceTab = 'dashboard' | 'properties' | 'sql' | 'statistics' | 'dependencies' | 'dependents' | 'data' | 'query';
type SelectionKind = 'server' | 'database' | 'schema' | 'group' | 'object' | 'function';
interface DraftColumn { name: string; type: string; nullable: boolean; default: string }
interface ExplorerSelection { kind: SelectionKind; title: string; schema?: string; group?: string; object?: PgAdminObject; fn?: any }

@Component({
  selector: 'pg-admin',
  standalone: true,
  imports: [CommonModule, FormsModule, ClarityModule, CarbonIcon],
  styles: [`
    :host{display:block;min-width:0;color:#161616}.pga-app{border:1px solid #c6c6c6;background:#eef0f3;height:42rem;min-height:0;overflow:hidden;display:flex;flex-direction:column;box-shadow:0 1px 2px rgba(0,0,0,.08)}
    .pga-menu{height:2.15rem;display:flex;align-items:center;padding:0 .75rem;background:#0f62a0;color:#fff;flex:0 0 auto}.pga-menu strong{font-size:.78rem}
    .pga-toolbar{height:2.7rem;display:flex;align-items:center;gap:.25rem;padding:.3rem .5rem;background:#fff;border-bottom:1px solid #c6c6c6;flex:0 0 auto}.pga-tool{height:1.9rem;min-width:1.9rem;border:1px solid transparent;background:#fff;color:#262626;display:inline-flex;align-items:center;justify-content:center;gap:.35rem;padding:0 .45rem;font-size:.7rem}.pga-tool:hover{background:#e8f2fb;border-color:#8ab8d8}.pga-tool:disabled{opacity:.42}.pga-tool-sep{height:1.6rem;border-left:1px solid #c6c6c6;margin:0 .25rem}.pga-connection{margin-left:auto;display:flex;align-items:center;gap:.45rem;font-size:.68rem;color:#525252}.pga-connection b{color:#198038}
    .pga-body{display:grid;grid-template-columns:18rem minmax(0,1fr);min-height:0;overflow:hidden;flex:1 1 auto}.pga-browser{background:#fff;border-right:1px solid #a8a8a8;display:flex;flex-direction:column;min-width:0;min-height:0;overflow:hidden}.pga-browser-title{height:2.35rem;display:flex;align-items:center;justify-content:space-between;padding:0 .65rem;border-bottom:1px solid #c6c6c6;font-size:.76rem;font-weight:600;flex:0 0 auto}.pga-filter{height:2.35rem;display:flex;align-items:center;gap:.35rem;padding:.35rem .55rem;border-bottom:1px solid #e0e0e0;flex:0 0 auto}.pga-filter input{width:100%;height:1.65rem;border:1px solid #a8a8a8;padding:0 .45rem;font-size:.7rem}.pga-tree{min-height:0;overflow:auto;padding:.28rem 0 .8rem;flex:1 1 auto;font-size:.71rem}.pga-node{height:1.72rem;width:100%;border:0;background:transparent;display:flex;align-items:center;gap:.28rem;padding:0 .4rem;text-align:left;color:#262626}.pga-node:hover{background:#edf5ff}.pga-node.active{background:#d0e2ff;color:#0043ce}.pga-node .grow{flex:1;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.pga-node small{color:#6f6f6f}.pga-indent-1{padding-left:1rem}.pga-indent-2{padding-left:1.7rem}.pga-indent-3{padding-left:2.4rem}.pga-indent-4{padding-left:3.1rem}.pga-indent-5{padding-left:3.8rem}.pga-indent-6{padding-left:4.5rem}.pga-indent-7{padding-left:5.2rem}.pga-caret{display:inline-flex;width:.8rem}.pga-tree-empty{padding:.7rem 1rem;color:#6f6f6f}
    .pga-workspace{min-width:0;min-height:0;overflow:hidden;background:#f4f5f7;display:flex;flex-direction:column}.pga-tabs{height:2.4rem;display:flex;align-items:flex-end;gap:0;background:#fff;border-bottom:1px solid #a8a8a8;padding-left:.35rem;overflow-x:auto;flex:0 0 auto}.pga-tab{height:2.15rem;border:0;border-right:1px solid #e0e0e0;background:#fff;padding:0 .65rem;font-size:.7rem;white-space:nowrap}.pga-tab:hover{background:#f4f4f4}.pga-tab.active{color:#0f62a0;border-bottom:3px solid #0f62a0;font-weight:600}.pga-tab.contextual,.pga-tab.query{display:flex;align-items:center;gap:.35rem}.pga-tab.contextual{background:#f4f4f4}.pga-tab.query{background:#edf5ff}.pga-context{height:2.15rem;display:flex;align-items:center;gap:.4rem;padding:0 .8rem;background:#fff;border-bottom:1px solid #e0e0e0;font-size:.7rem;color:#525252;flex:0 0 auto}.pga-context strong{color:#161616}.pga-content{min-height:0;flex:1 1 auto;overflow:auto;padding:.9rem;background:#f4f5f7}.pga-panel{background:#fff;border:1px solid #c6c6c6;min-height:31rem}.pga-panel-head{min-height:2.55rem;display:flex;align-items:center;justify-content:space-between;padding:.55rem .75rem;border-bottom:1px solid #c6c6c6}.pga-panel-head h3{margin:0;font-size:.88rem}.pga-panel-body{padding:.8rem}.pga-kpis{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:.65rem;margin-bottom:.8rem}.pga-kpi{background:#f4f4f4;border-left:3px solid #0f62a0;padding:.7rem}.pga-kpi span{display:block;color:#525252;font-size:.65rem}.pga-kpi strong{display:block;margin-top:.2rem;font-size:.95rem}.pga-section{border:1px solid #e0e0e0;margin-bottom:.75rem}.pga-section h4{margin:0;padding:.5rem .65rem;background:#f4f4f4;border-bottom:1px solid #e0e0e0;font-size:.75rem}.pga-grid{display:grid;grid-template-columns:11rem 1fr}.pga-grid dt,.pga-grid dd{margin:0;padding:.48rem .65rem;border-bottom:1px solid #e8e8e8;font-size:.7rem}.pga-grid dt{color:#525252;background:#fafafa}.pga-table{width:100%;border-collapse:collapse;background:#fff}.pga-table th,.pga-table td{padding:.43rem .55rem;border:1px solid #e0e0e0;text-align:left;font-size:.68rem;vertical-align:top}.pga-table th{background:#f4f4f4;font-weight:600}.pga-empty{padding:2rem;text-align:center;color:#6f6f6f;font-size:.72rem}.pga-code{margin:0;min-height:20rem;white-space:pre-wrap;word-break:break-word;background:#1f2933;color:#e8edf2;padding:.85rem;font:12px/1.55 Consolas,monospace}.pga-note{padding:.65rem .75rem;background:#edf5ff;border-left:3px solid #0f62a0;font-size:.7rem}.pga-status{display:inline-flex;align-items:center;gap:.3rem;color:#198038;font-size:.68rem}.pga-status:before{content:'';width:.42rem;height:.42rem;border-radius:50%;background:#24a148}
    .pga-query{display:grid;grid-template-rows:auto minmax(12rem,1fr) auto minmax(9rem,.8fr);height:31rem}.pga-querybar{display:flex;align-items:center;gap:.25rem;padding:.35rem .45rem;background:#fff;border-bottom:1px solid #c6c6c6}.pga-editor-wrap{display:grid;grid-template-columns:2.2rem 1fr;background:#fff;border-bottom:1px solid #a8a8a8}.pga-lines{padding:.65rem .35rem;background:#f4f4f4;color:#8d8d8d;text-align:right;font:12px/1.55 Consolas,monospace}.pga-editor{width:100%;height:100%;min-height:12rem;border:0;resize:none;padding:.65rem;font:12px/1.55 Consolas,monospace;outline:none}.pga-result-tabs{height:2rem;display:flex;background:#fff;border-bottom:1px solid #c6c6c6}.pga-result-tab{border:0;background:#fff;padding:0 .75rem;font-size:.68rem}.pga-result-tab.active{border-bottom:2px solid #0f62a0;color:#0f62a0}.pga-output{overflow:auto;background:#fff}.pga-message{padding:.75rem;font:12px/1.5 Consolas,monospace}.pga-error{color:#da1e28}.pga-success{color:#198038}
    .pga-data-view{display:grid;grid-template-rows:auto 1fr auto;height:31rem;background:#fff}.pga-data-toolbar{display:flex;align-items:center;gap:.45rem;padding:.38rem .5rem;border-bottom:1px solid #c6c6c6;background:#fff}.pga-data-toolbar label{display:flex;align-items:center;gap:.35rem;margin-left:auto;font-size:.68rem;color:#525252}.pga-data-toolbar select{height:1.8rem;border:1px solid #8d8d8d;background:#fff;font-size:.68rem}.pga-data-grid{min-width:100%;overflow:auto;background:#fff}.pga-data-grid .pga-table th{position:sticky;top:0;z-index:1;background:#e8e8e8}.pga-data-grid .pga-table td{white-space:nowrap;max-width:28rem;overflow:hidden;text-overflow:ellipsis}.pga-data-status{display:flex;align-items:center;justify-content:space-between;min-height:2rem;padding:.35rem .6rem;border-top:1px solid #c6c6c6;background:#f4f4f4;color:#525252;font-size:.67rem}
    .pga-modal-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:.7rem}.pga-modal-grid label{display:flex;flex-direction:column;gap:.25rem;font-size:.7rem}.pga-modal-grid input,.pga-modal-grid select{width:100%;min-height:2rem}.pga-columns{grid-column:1/-1;border-top:1px solid #e0e0e0;padding-top:.65rem}.pga-column{display:grid;grid-template-columns:1fr 1.3fr .85fr .55fr auto;gap:.4rem;align-items:end;margin-bottom:.45rem}.pga-wide{grid-column:1/-1}.pga-preview{max-height:8rem;overflow:auto}.pga-risk{padding:.55rem .65rem;background:#fff8e1;border-left:3px solid #f1c21b;font-size:.7rem;margin-top:.65rem}
    @media(max-width:1050px){.pga-body{grid-template-columns:15rem minmax(0,1fr)}.pga-kpis{grid-template-columns:repeat(2,1fr)}}@media(max-width:760px){.pga-body{display:block;height:auto}.pga-browser{height:18rem;border-right:0;border-bottom:1px solid #a8a8a8}.pga-workspace{min-height:34rem}.pga-modal-grid,.pga-column{grid-template-columns:1fr}.pga-wide,.pga-columns{grid-column:auto}}
  `],
  template: `
    <section class="pga-app" aria-label="PostgreSQL administration workspace">
      <div class="pga-menu"><strong>pgAdmin</strong></div>
      <div class="pga-toolbar">
        <button class="pga-tool" type="button" title="Refresh object explorer" aria-label="Refresh object explorer" (click)="svc.refresh()" [disabled]="svc.state()==='loading'"><os-cicon [icon]="iRenew" [size]="16"/></button>
        <button class="pga-tool" type="button" title="Create object" (click)="openCreate()"><os-cicon [icon]="iAdd" [size]="16"/> Create</button>
        <button class="pga-tool" type="button" title="Drop selected object" (click)="openDrop()" [disabled]="!canDropSelected()"><os-cicon [icon]="iTrash" [size]="16"/> Drop</button>
        <span class="pga-tool-sep"></span>
        <button class="pga-tool" type="button" title="Open Query Tool" (click)="activeTab.set('query')"><os-cicon [icon]="iCode" [size]="16"/> Query Tool</button>
        <button class="pga-tool" type="button" title="View selected table data" (click)="openDataView()" [disabled]="!canViewData()"><os-cicon [icon]="iTable" [size]="16"/> View Data</button>
        <div class="pga-connection"><span>{{svc.catalog()?.cluster || 'pgc-foundation-data-pg'}}</span><b>Connected</b></div>
      </div>
      <clr-alert *ngIf="svc.state()==='error'" clrAlertType="danger" [clrAlertClosable]="false"><clr-alert-item><span class="alert-text">{{svc.error()}}</span><div class="alert-actions"><button class="btn alert-action" (click)="svc.refresh()">Retry</button></div></clr-alert-item></clr-alert>
      <div class="pga-body" *ngIf="svc.catalog() as catalog">
        <aside class="pga-browser" aria-label="Object Explorer">
          <div class="pga-browser-title"><span>Object Explorer</span><button class="pga-tool" type="button" aria-label="Refresh" (click)="svc.refresh()"><os-cicon [icon]="iRenew" [size]="14"/></button></div>
          <label class="pga-filter"><os-cicon [icon]="iSearch" [size]="14"/><input [(ngModel)]="treeFilter" aria-label="Filter objects" placeholder="Filter objects" /></label>
          <div class="pga-tree">
            <button class="pga-node" type="button" (click)="toggle('servers')" [attr.aria-expanded]="nodeExpanded('servers')"><span class="pga-caret"><os-cicon [icon]="nodeExpanded('servers')?iDown:iRight" [size]="12"/></span><os-cicon [icon]="nodeExpanded('servers')?iFolderOpen:iFolder" [size]="15"/><span class="grow">Servers</span><small>1</small></button>
            <ng-container *ngIf="nodeExpanded('servers')">
              <button class="pga-node pga-indent-1" [class.active]="selection().kind==='server'" type="button" (click)="selectServer()" [attr.aria-expanded]="nodeExpanded(serverKey)"><span class="pga-caret"><os-cicon [icon]="nodeExpanded(serverKey)?iDown:iRight" [size]="12"/></span><os-cicon [icon]="iServer" [size]="15"/><span class="grow">Foundation PostgreSQL</span></button>
              <ng-container *ngIf="nodeExpanded(serverKey)">
              <button class="pga-node pga-indent-2" type="button" (click)="toggle(databasesKey)" [attr.aria-expanded]="nodeExpanded(databasesKey)"><span class="pga-caret"><os-cicon [icon]="nodeExpanded(databasesKey)?iDown:iRight" [size]="12"/></span><os-cicon [icon]="nodeExpanded(databasesKey)?iFolderOpen:iFolder" [size]="15"/><span class="grow">Databases</span><small>{{catalog.databases.length}}</small></button>
              <ng-container *ngIf="nodeExpanded(databasesKey)"><ng-container *ngFor="let db of filteredDatabases()">
                <button class="pga-node pga-indent-3" [class.active]="selection().kind==='database'&&selection().title===db.name" type="button" (click)="selectDatabase(db.name)" [attr.aria-expanded]="nodeExpanded(databaseKey(db.name))"><span class="pga-caret"><os-cicon [icon]="nodeExpanded(databaseKey(db.name))?iDown:iRight" [size]="12"/></span><os-cicon [icon]="iDatabase" [size]="15"/><span class="grow">{{db.name}}</span></button>
                <ng-container *ngIf="nodeExpanded(databaseKey(db.name))&&db.name===svc.selectedDatabase()">
                  <button class="pga-node pga-indent-4" type="button" (click)="toggle(schemasKey(db.name))" [attr.aria-expanded]="nodeExpanded(schemasKey(db.name))"><span class="pga-caret"><os-cicon [icon]="nodeExpanded(schemasKey(db.name))?iDown:iRight" [size]="12"/></span><os-cicon [icon]="nodeExpanded(schemasKey(db.name))?iFolderOpen:iFolder" [size]="15"/><span class="grow">Schemas</span><small>{{filteredSchemas().length}}</small></button>
                  <ng-container *ngIf="nodeExpanded(schemasKey(db.name))"><ng-container *ngFor="let schema of filteredSchemas()">
                    <button class="pga-node pga-indent-5" [class.active]="selection().kind==='schema'&&selection().schema===schema.name" type="button" (click)="selectSchema(schema.name)" [attr.aria-expanded]="nodeExpanded(schemaKey(db.name,schema.name))"><span class="pga-caret"><os-cicon [icon]="nodeExpanded(schemaKey(db.name,schema.name))?iDown:iRight" [size]="12"/></span><os-cicon [icon]="nodeExpanded(schemaKey(db.name,schema.name))?iFolderOpen:iFolder" [size]="15"/><span class="grow">{{schema.name}}</span></button>
                    <ng-container *ngIf="nodeExpanded(schemaKey(db.name,schema.name))">
                      <ng-container *ngFor="let group of groupsFor(schema.name); trackBy: trackGroup">
                        <button class="pga-node pga-indent-6" [class.active]="selection().kind==='group'&&selection().group===group.label" type="button" (click)="selectGroup(schema.name,group.label)" [attr.aria-expanded]="nodeExpanded(groupKey(db.name,schema.name,group.label))"><span class="pga-caret"><os-cicon [icon]="nodeExpanded(groupKey(db.name,schema.name,group.label))?iDown:iRight" [size]="12"/></span><os-cicon [icon]="group.label==='Tables'||group.label==='Views'?iTable:iDocument" [size]="14"/><span class="grow">{{group.label}}</span><small>{{group.items.length}}</small></button>
                        <ng-container *ngIf="nodeExpanded(groupKey(db.name,schema.name,group.label))"><button *ngFor="let object of group.items; trackBy: trackObject" class="pga-node pga-indent-7" [class.active]="isSelected(object)" type="button" (click)="selectObject(object)"><span class="pga-caret"></span><os-cicon [icon]="iDocument" [size]="13"/><span class="grow">{{object.name}}</span></button></ng-container>
                      </ng-container>
                      <button class="pga-node pga-indent-6" [class.active]="selection().kind==='group'&&selection().group==='Functions'" type="button" (click)="selectGroup(schema.name,'Functions')" [attr.aria-expanded]="nodeExpanded(groupKey(db.name,schema.name,'Functions'))"><span class="pga-caret"><os-cicon [icon]="nodeExpanded(groupKey(db.name,schema.name,'Functions'))?iDown:iRight" [size]="12"/></span><os-cicon [icon]="iFunction" [size]="14"/><span class="grow">Functions</span><small>{{functionsFor(schema.name).length}}</small></button>
                      <ng-container *ngIf="nodeExpanded(groupKey(db.name,schema.name,'Functions'))"><button *ngFor="let fn of functionsFor(schema.name)" class="pga-node pga-indent-7" [class.active]="selection().kind==='function'&&selection().title===fn.name" type="button" (click)="selectFunction(fn)"><span class="pga-caret"></span><os-cicon [icon]="iFunction" [size]="13"/><span class="grow">{{fn.name}}</span></button></ng-container>
                    </ng-container>
                  </ng-container></ng-container>
                </ng-container>
              </ng-container></ng-container>
              </ng-container>
            </ng-container>
            <p class="pga-tree-empty" *ngIf="treeFilter && !filteredDatabases().length">No matching objects</p>
          </div>
        </aside>
        <section class="pga-workspace">
          <nav class="pga-tabs" aria-label="Object workspace tabs">
            <button *ngFor="let tab of workspaceTabs" class="pga-tab" [class.active]="activeTab()===tab.id" type="button" (click)="activeTab.set(tab.id)">{{tab.label}}</button>
            <button *ngIf="canViewData()" class="pga-tab contextual" [class.active]="activeTab()==='data'" type="button" (click)="openDataView()" [title]="'Data View - '+svc.selectedObject()?.name"><os-cicon [icon]="iTable" [size]="14"/> Data View</button>
            <button class="pga-tab query" [class.active]="activeTab()==='query'" type="button" (click)="activeTab.set('query')"><os-cicon [icon]="iCode" [size]="14"/> Query - {{svc.selectedDatabase()}}</button>
          </nav>
          <div class="pga-context"><os-cicon [icon]="selectionIcon()" [size]="14"/><strong>{{selection().title || svc.selectedDatabase()}}</strong><span>{{selection().kind}}</span><span *ngIf="selection().schema">· {{selection().schema}}</span></div>
          <div class="pga-content">
            <section class="pga-panel" *ngIf="activeTab()==='dashboard'">
              <div class="pga-panel-head"><h3>Dashboard</h3><span class="pga-status">Live catalog</span></div>
              <div class="pga-panel-body">
                <div class="pga-kpis"><div class="pga-kpi"><span>Database</span><strong>{{catalog.selectedDatabase}}</strong></div><div class="pga-kpi"><span>Schemas</span><strong>{{catalog.schemas.length}}</strong></div><div class="pga-kpi"><span>Objects</span><strong>{{catalog.objects.length}}</strong></div><div class="pga-kpi"><span>Sessions</span><strong>{{sessionCount()}}</strong></div></div>
                <section class="pga-section"><h4>Server activity</h4><table class="pga-table"><thead><tr><th>Database</th><th>State</th><th>Sessions</th></tr></thead><tbody><tr *ngFor="let row of catalog.activity"><td>{{row.database||'shared'}}</td><td>{{row.state}}</td><td>{{row.sessions}}</td></tr></tbody></table></section>
                <section class="pga-section"><h4>Server information</h4><dl class="pga-grid"><dt>Server version</dt><dd>{{catalog.settings.server_version}}</dd><dt>Encoding</dt><dd>{{catalog.settings.server_encoding}}</dd><dt>Time zone</dt><dd>{{catalog.settings.timezone}}</dd><dt>Connected user</dt><dd>{{catalog.settings.username}}</dd></dl></section>
              </div>
            </section>
            <section class="pga-panel" *ngIf="activeTab()==='properties'">
              <div class="pga-panel-head"><h3>Properties</h3><button class="pga-tool" type="button" (click)="openManage()" *ngIf="selection().kind==='object'"><os-cicon [icon]="iCode" [size]="14"/> Manage</button></div>
              <div class="pga-panel-body">
                <section class="pga-section"><h4>General</h4><dl class="pga-grid"><dt>Name</dt><dd>{{selection().title}}</dd><dt>Object type</dt><dd>{{selection().kind}}</dd><dt>Schema</dt><dd>{{selection().schema||'—'}}</dd><dt>Owner</dt><dd>{{selectionOwner()}}</dd><dt>Comment</dt><dd>{{selectionComment()||'—'}}</dd></dl></section>
                <ng-container *ngIf="svc.selectedObject() as object"><section class="pga-section"><h4>Definition</h4><dl class="pga-grid"><dt>Persistence</dt><dd>{{object.persistence||'—'}}</dd><dt>Tablespace</dt><dd>{{object.tablespace||'—'}}</dd><dt>Estimated rows</dt><dd>{{object.estimated_rows}}</dd><dt>Total size</dt><dd>{{formatBytes(object.size_bytes)}}</dd></dl></section><section class="pga-section"><h4>Columns</h4><table class="pga-table"><thead><tr><th>#</th><th>Name</th><th>Data type</th><th>Nullable</th><th>Default</th></tr></thead><tbody><tr *ngFor="let column of svc.selectedColumns()"><td>{{column.ordinal_position}}</td><td>{{column.name}}</td><td>{{column.data_type}}{{column.data_type==='USER-DEFINED'?' · '+column.udt_name:''}}</td><td>{{column.nullable?'Yes':'No'}}</td><td>{{column.column_default||'—'}}</td></tr></tbody></table></section></ng-container>
                <ng-container *ngIf="selection().kind==='function'&&selection().fn as fn"><section class="pga-section"><h4>Function definition</h4><dl class="pga-grid"><dt>Arguments</dt><dd>{{fn.arguments||'—'}}</dd><dt>Returns</dt><dd>{{fn.result}}</dd><dt>Language</dt><dd>{{fn.language}}</dd><dt>Owner</dt><dd>{{fn.owner}}</dd></dl></section></ng-container>
              </div>
            </section>
            <section class="pga-panel" *ngIf="activeTab()==='sql'"><div class="pga-panel-head"><h3>SQL</h3><span>Generated from live catalog</span></div><pre class="pga-code">{{objectSql()}}</pre></section>
            <section class="pga-panel" *ngIf="activeTab()==='statistics'"><div class="pga-panel-head"><h3>Statistics</h3><span class="pga-status">Current snapshot</span></div><div class="pga-panel-body"><div class="pga-kpis"><div class="pga-kpi"><span>Estimated rows</span><strong>{{svc.selectedObject()?.estimated_rows||'—'}}</strong></div><div class="pga-kpi"><span>Total size</span><strong>{{formatBytes(svc.selectedObject()?.size_bytes||0)}}</strong></div><div class="pga-kpi"><span>Columns</span><strong>{{svc.selectedColumns().length}}</strong></div><div class="pga-kpi"><span>Indexes</span><strong>{{svc.selectedIndexes().length}}</strong></div></div><section class="pga-section"><h4>Session distribution</h4><table class="pga-table"><thead><tr><th>State</th><th>Sessions</th></tr></thead><tbody><tr *ngFor="let row of databaseActivity()"><td>{{row.state}}</td><td>{{row.sessions}}</td></tr></tbody></table></section></div></section>
            <section class="pga-panel" *ngIf="activeTab()==='dependencies'"><div class="pga-panel-head"><h3>Dependencies</h3></div><div class="pga-panel-body"><p class="pga-note">Objects required by the selected object. DROP remains RESTRICT-only.</p><table class="pga-table"><thead><tr><th>Type</th><th>Schema</th><th>Name</th><th>Dependency</th></tr></thead><tbody><tr *ngFor="let row of svc.selectedDependencies()"><td>{{row.referenced_kind}}</td><td>{{row.referenced_schema}}</td><td>{{row.referenced_object}}</td><td>{{row.dependency_type}}</td></tr></tbody></table><p class="pga-empty" *ngIf="!svc.selectedDependencies().length">No catalog dependencies reported for this selection.</p></div></section>
            <section class="pga-panel" *ngIf="activeTab()==='dependents'"><div class="pga-panel-head"><h3>Dependents</h3></div><div class="pga-panel-body"><p class="pga-note">Objects that depend on the selected object.</p><table class="pga-table"><thead><tr><th>Schema</th><th>Name</th><th>Dependency</th></tr></thead><tbody><tr *ngFor="let row of svc.selectedDependents()"><td>{{row.schema}}</td><td>{{row.object}}</td><td>{{row.dependency_type}}</td></tr></tbody></table><p class="pga-empty" *ngIf="!svc.selectedDependents().length">No dependent objects reported for this selection.</p></div></section>
            <section class="pga-panel" *ngIf="activeTab()==='data'">
              <div class="pga-data-view"><div class="pga-data-toolbar"><button class="pga-tool" type="button" title="Reload table data" (click)="reloadDataView()" [disabled]="svc.dataState()==='loading'"><os-cicon [icon]="iRenew" [size]="15"/> Refresh</button><span><strong>View Data</strong> · {{svc.selectedDatabase()}} / {{svc.selectedObject()?.schema}}.{{svc.selectedObject()?.name}}</span><label>Row limit <select [(ngModel)]="dataLimit" (change)="reloadDataView()"><option *ngFor="let limit of dataLimits" [ngValue]="limit">{{limit}}</option></select></label></div><div class="pga-data-grid"><table class="pga-table" *ngIf="svc.dataResult() as result"><thead><tr><th>#</th><th *ngFor="let field of result.fields">{{field.name}}</th></tr></thead><tbody><tr *ngFor="let row of result.rows; let i=index"><td>{{i+1}}</td><td *ngFor="let field of result.fields" [title]="cell(row,field.name)">{{cell(row,field.name)}}</td></tr></tbody></table><p class="pga-empty" *ngIf="svc.dataState()==='loading'">Loading table data…</p><p class="pga-empty pga-error" *ngIf="svc.dataState()==='error'">{{svc.dataError()}}</p><p class="pga-empty" *ngIf="svc.dataState()==='done'&&svc.dataResult()?.rowCount===0">This table has no rows.</p></div><div class="pga-data-status"><span>{{dataStatus()}}</span><span>Read-only · {{dataLimit}} row limit</span></div></div>
            </section>
            <section class="pga-panel" *ngIf="activeTab()==='query'">
              <div class="pga-query"><div class="pga-querybar"><button class="pga-tool" type="button" title="Execute" (click)="runQuery()" [disabled]="!querySql.trim()||svc.queryState()==='running'"><os-cicon [icon]="iPlay" [size]="15"/> Execute</button><button class="pga-tool" type="button" title="Explain" (click)="runExplain()" [disabled]="!querySql.trim()||svc.queryState()==='running'"><os-cicon [icon]="iDocument" [size]="15"/> Explain</button><button class="pga-tool" type="button" title="Clear editor" (click)="clearQuery()">Clear</button><span class="pga-tool-sep"></span><span>{{svc.selectedDatabase()}} · read-only · 10s timeout · 500 rows</span></div><div class="pga-editor-wrap"><div class="pga-lines">1</div><textarea class="pga-editor" [(ngModel)]="querySql" aria-label="SQL Query Editor" spellcheck="false"></textarea></div><div class="pga-result-tabs"><button class="pga-result-tab" [class.active]="resultTab==='data'" type="button" (click)="resultTab='data'">Data Output</button><button class="pga-result-tab" [class.active]="resultTab==='messages'" type="button" (click)="resultTab='messages'">Messages</button><button class="pga-result-tab" [class.active]="resultTab==='history'" type="button" (click)="resultTab='history'">Query History</button></div><div class="pga-output"><ng-container *ngIf="resultTab==='data'"><table class="pga-table" *ngIf="svc.queryResult() as result"><thead><tr><th *ngFor="let field of result.fields">{{field.name}}</th></tr></thead><tbody><tr *ngFor="let row of result.rows"><td *ngFor="let field of result.fields">{{cell(row,field.name)}}</td></tr></tbody></table><p class="pga-empty" *ngIf="!svc.queryResult()">Execute a query to view data output.</p></ng-container><div class="pga-message" *ngIf="resultTab==='messages'"><span [class.pga-error]="svc.queryState()==='error'" [class.pga-success]="svc.queryState()==='done'">{{queryMessage()}}</span></div><table class="pga-table" *ngIf="resultTab==='history'"><thead><tr><th>Time</th><th>SQL</th><th>Result</th></tr></thead><tbody><tr *ngFor="let item of queryHistory()"><td>{{item.time}}</td><td>{{item.sql}}</td><td>{{item.result}}</td></tr></tbody></table></div></div>
            </section>
          </div>
        </section>
      </div>
    </section>

    <clr-modal [(clrModalOpen)]="manageOpen" [clrModalSize]="'lg'">
      <h3 class="modal-title">{{actionTitle()}}</h3>
      <div class="modal-body"><p class="pga-note">Typed PostgreSQL action · recent MFA and an audit reason are required.</p><div class="pga-modal-grid">
        <label><span>Action</span><select [(ngModel)]="action"><option value="create-schema">Create schema</option><option value="create-table">Create table</option><option value="create-index">Create index</option><option value="drop-index">Drop index</option><option value="drop-table">Drop table</option><option value="drop-view">Drop view</option><option value="drop-materialized-view">Drop materialized view</option><option value="drop-sequence">Drop sequence</option><option value="drop-foreign-table">Drop foreign table</option><option value="drop-schema">Drop schema</option></select></label>
        <label><span>Schema</span><input [(ngModel)]="draftSchema" /></label><label *ngIf="action!=='create-schema'&&action!=='drop-schema'"><span>{{action.includes('index')?'Index':'Table'}} name</span><input [(ngModel)]="draftName" /></label><label *ngIf="action==='create-index'"><span>Table</span><input [(ngModel)]="draftTable" /></label><label *ngIf="action==='create-index'"><span>Index columns</span><input [(ngModel)]="draftIndexColumns" placeholder="created_at, id" /></label><label *ngIf="action==='create-index'"><span>Unique</span><select [(ngModel)]="draftUnique"><option [ngValue]="false">No</option><option [ngValue]="true">Yes</option></select></label>
        <div class="pga-columns" *ngIf="action==='create-table'"><div class="pga-column" *ngFor="let column of draftColumns(); let i=index"><label><span>Column</span><input [(ngModel)]="column.name" /></label><label><span>Type</span><select [(ngModel)]="column.type"><option *ngFor="let type of columnTypes" [value]="type">{{type}}</option></select></label><label><span>Default</span><select [(ngModel)]="column.default"><option value="">None</option><option value="now()">now()</option><option value="gen_random_uuid()">gen_random_uuid()</option><option value="true">true</option><option value="false">false</option></select></label><label><span>Nullable</span><input type="checkbox" [(ngModel)]="column.nullable" /></label><button class="btn btn-sm" type="button" (click)="removeColumn(i)" [disabled]="draftColumns().length===1">Remove</button></div><button class="btn btn-sm" type="button" (click)="addColumn()">Add column</button></div>
        <label class="pga-wide"><span>Change reason</span><input [(ngModel)]="reason" maxlength="500" placeholder="At least 8 characters" /></label><div class="pga-wide"><span>SQL preview</span><pre class="pga-code pga-preview">{{sqlPreview()}}</pre></div>
      </div><div class="pga-risk" *ngIf="action.startsWith('drop-')">DROP uses RESTRICT only. PostgreSQL rejects the request if dependent objects exist.</div><p [class.pga-success]="svc.actionState()==='done'" [class.pga-error]="svc.actionState()==='error'">{{svc.actionResult()}}</p></div>
      <div class="modal-footer"><button class="btn btn-outline" type="button" (click)="manageOpen=false">Cancel</button><button class="btn" [class.btn-danger]="action.startsWith('drop-')" [class.btn-primary]="!action.startsWith('drop-')" type="button" (click)="runAction()" [disabled]="!actionReady()||svc.actionState()==='running'">{{svc.actionState()==='running'?'Running…':'Execute'}}</button></div>
    </clr-modal>
  `,
})
export class PgAdminTab implements OnInit {
  readonly svc = inject(PgAdminService);
  readonly iAdd=Add16; readonly iDown=ChevronDown16; readonly iRight=ChevronRight16; readonly iCode=Code16; readonly iDatabase=Db2Database16; readonly iDocument=Document16; readonly iFolder=Folder16; readonly iFolderOpen=FolderOpen16; readonly iFunction=Function16; readonly iPlay=Play16; readonly iRenew=Renew16; readonly iSearch=Search16; readonly iServer=ServerProxy16; readonly iTable=Table16; readonly iTrash=TrashCan16;
  readonly workspaceTabs: Array<{id: WorkspaceTab; label: string}> = [{id:'dashboard',label:'Dashboard'},{id:'properties',label:'Properties'},{id:'sql',label:'SQL'},{id:'statistics',label:'Statistics'},{id:'dependencies',label:'Dependencies'},{id:'dependents',label:'Dependents'}];
  readonly activeTab = signal<WorkspaceTab>('dashboard');
  readonly selection = signal<ExplorerSelection>({kind:'database',title:''});
  readonly serverKey='server:foundation'; readonly databasesKey='databases';
  readonly expandedNodes = signal(new Set<string>(['servers',this.serverKey,this.databasesKey]));
  readonly draftColumns = signal<DraftColumn[]>([{name:'id',type:'bigserial',nullable:false,default:''}]);
  readonly queryHistory = signal<Array<{time:string;sql:string;result:string}>>([]);
  readonly columnTypes = ['bigint','bigserial','boolean','bytea','date','double precision','integer','json','jsonb','numeric','real','smallint','text','time','timestamp','timestamp with time zone','uuid','varchar(255)'];
  readonly dataLimits=[100,250,500];
  treeFilter=''; manageOpen=false; resultTab:'data'|'messages'|'history'='data';
  action:ActionId='create-table'; draftSchema='public'; draftName=''; draftTable=''; draftIndexColumns=''; draftUnique=false; reason=''; querySql='SELECT current_database(), current_user, version();'; dataLimit=100;
  ngOnInit(): void { void this.initialize(); }
  async initialize(){ if(!this.svc.catalog()) await this.svc.refresh(); this.selection.set({kind:'database',title:this.svc.selectedDatabase()}); this.expandPath(this.svc.selectedDatabase(),this.svc.selectedSchema()); }
  expanded(key:string){return this.expandedNodes().has(key)}
  nodeExpanded(key:string){return!!this.treeFilter.trim()||this.expanded(key)}
  toggle(key:string){this.expandedNodes.update(current=>{const next=new Set(current);next.has(key)?next.delete(key):next.add(key);return next})}
  databaseKey(database:string){return`database:${database}`}
  schemasKey(database:string){return`schemas:${database}`}
  schemaKey(database:string,schema:string){return`schema:${database}:${schema}`}
  groupKey(database:string,schema:string,group:string){return`group:${database}:${schema}:${group}`}
  expandPath(database:string,schema:string){this.expandedNodes.update(current=>new Set([...current,'servers',this.serverKey,this.databasesKey,this.databaseKey(database),this.schemasKey(database),this.schemaKey(database,schema),this.groupKey(database,schema,'Tables')]))}
  filteredDatabases(){const q=this.treeFilter.trim().toLowerCase(),catalog=this.svc.catalog();if(!catalog)return[];if(!q)return catalog.databases;return catalog.databases.filter(db=>db.name.toLowerCase().includes(q)||catalog.objects.some(o=>o.name.toLowerCase().includes(q)||o.schema.toLowerCase().includes(q)))}
  filteredSchemas(){const q=this.treeFilter.trim().toLowerCase(),catalog=this.svc.catalog();if(!catalog)return[];if(!q)return catalog.schemas;return catalog.schemas.filter(s=>s.name.toLowerCase().includes(q)||catalog.objects.some(o=>o.schema===s.name&&o.name.toLowerCase().includes(q)))}
  groupsFor(schema:string){const objects=(this.svc.catalog()?.objects??[]).filter(o=>o.schema===schema&&(!this.treeFilter.trim()||o.name.toLowerCase().includes(this.treeFilter.trim().toLowerCase())));const groups=[['Tables',['table','partitioned table']],['Views',['view','materialized view']],['Sequences',['sequence']],['Foreign Tables',['foreign table']]] as const;return groups.map(([label,kinds])=>({label,items:objects.filter(o=>(kinds as readonly string[]).includes(o.kind))}))}
  trackGroup(_index:number,group:{label:string}){return group.label}
  trackObject(_index:number,object:PgAdminObject){return`${object.schema}:${object.kind}:${object.name}`}
  functionsFor(schema:string){const q=this.treeFilter.trim().toLowerCase();return(this.svc.catalog()?.functions??[]).filter((fn:any)=>fn.schema===schema&&(!q||fn.name.toLowerCase().includes(q)))}
  selectServer(){this.svc.selectedObject.set(null);this.selection.set({kind:'server',title:'Foundation PostgreSQL'});this.activeTab.set('dashboard');this.toggle(this.serverKey)}
  async selectDatabase(name:string){const changed=name!==this.svc.selectedDatabase();if(changed){this.svc.selectedDatabase.set(name);this.svc.selectedObject.set(null);await this.svc.refresh(name);this.expandPath(name,this.svc.selectedSchema())}else this.toggle(this.databaseKey(name));this.selection.set({kind:'database',title:name});this.activeTab.set('dashboard')}
  selectSchema(schema:string){this.svc.selectedSchema.set(schema);this.svc.selectedObject.set(null);this.selection.set({kind:'schema',title:schema,schema});this.draftSchema=schema;this.activeTab.set('properties');this.toggle(this.schemaKey(this.svc.selectedDatabase(),schema))}
  selectGroup(schema:string,group:string){this.svc.selectedSchema.set(schema);this.svc.selectedObject.set(null);this.selection.set({kind:'group',title:group,schema,group});this.activeTab.set('properties');this.toggle(this.groupKey(this.svc.selectedDatabase(),schema,group))}
  async selectObject(object:PgAdminObject){this.svc.selectedSchema.set(object.schema);this.svc.selectedObject.set(object);this.selection.set({kind:'object',title:object.name,schema:object.schema,object});if(this.canViewData())await this.openDataView();else this.activeTab.set('properties')}
  selectFunction(fn:any){this.svc.selectedObject.set(null);this.selection.set({kind:'function',title:fn.name,schema:fn.schema,fn});this.activeTab.set('properties')}
  isSelected(object:PgAdminObject){return this.svc.selectedObject()?.schema===object.schema&&this.svc.selectedObject()?.name===object.name}
  selectionIcon(){const kind=this.selection().kind;return kind==='server'?this.iServer:kind==='database'?this.iDatabase:kind==='schema'||kind==='group'?this.iFolder:kind==='function'?this.iFunction:this.iTable}
  selectionOwner(){return this.selection().object?.owner||this.selection().fn?.owner||this.svc.catalog()?.databases.find(db=>db.name===this.svc.selectedDatabase())?.owner||'—'}
  selectionComment(){return this.selection().object?.comment||this.selection().fn?.comment||''}
  sessionCount(){return(this.svc.catalog()?.activity??[]).reduce((sum:number,row:any)=>sum+Number(row.sessions||0),0)}
  databaseActivity(){return(this.svc.catalog()?.activity??[]).filter((row:any)=>row.database===this.svc.selectedDatabase())}
  formatBytes(value:string|number){const bytes=Number(value||0);if(bytes>=1024**3)return`${(bytes/1024**3).toFixed(2)} GiB`;if(bytes>=1024**2)return`${(bytes/1024**2).toFixed(1)} MiB`;if(bytes>=1024)return`${(bytes/1024).toFixed(1)} KiB`;return`${bytes} B`}
  objectSql(){const fn=this.selection().fn;if(fn?.definition)return fn.definition;const object=this.svc.selectedObject();if(!object)return`-- Select a table, view, sequence, or function in Object Explorer.\n-- Live SQL definitions are shown here.`;if(object.definition){const verb=object.kind==='materialized view'?'CREATE MATERIALIZED VIEW':'CREATE OR REPLACE VIEW';return`${verb} "${object.schema}"."${object.name}" AS\n${object.definition};`}if(object.kind==='table'||object.kind==='partitioned table'){const columns=this.svc.selectedColumns().map((c:any)=>`  "${c.name}" ${c.data_type==='USER-DEFINED'?c.udt_name:c.data_type}${c.nullable?'':' NOT NULL'}${c.column_default?' DEFAULT '+c.column_default:''}`);const constraints=this.svc.selectedConstraints().map((c:any)=>`  CONSTRAINT "${c.name}" ${c.definition}`);const indexes=this.svc.selectedIndexes().map((i:any)=>i.definition+';').join('\n');return`CREATE TABLE "${object.schema}"."${object.name}" (\n${[...columns,...constraints].join(',\n')}\n);${indexes?'\n\n'+indexes:''}`}return`-- ${object.kind} "${object.schema}"."${object.name}"\n-- Definition is not exposed by the current PostgreSQL catalog.`}
  cell(row:Record<string,unknown>,key:string){const value=row[key];if(value===null||value===undefined)return'NULL';return typeof value==='object'?JSON.stringify(value):String(value)}
  canViewData(){return['table','partitioned table','view','materialized view','foreign table'].includes(this.svc.selectedObject()?.kind||'')}
  async openDataView(){const object=this.svc.selectedObject();if(!object||!this.canViewData())return;this.activeTab.set('data');await this.svc.loadData(object,this.dataLimit)}
  async reloadDataView(){const object=this.svc.selectedObject();if(!object||!this.canViewData())return;await this.svc.loadData(object,this.dataLimit)}
  dataStatus(){const result=this.svc.dataResult();if(this.svc.dataState()==='loading')return'Loading data…';if(this.svc.dataState()==='error')return this.svc.dataError();if(result)return`${result.rowCount} rows loaded in ${result.durationMs}ms${result.truncated?' · result truncated':''}`;return'Select a table or view to load data.'}
  async runQuery(){const sql=this.querySql.trim();await this.svc.runQuery(sql);this.resultTab=this.svc.queryState()==='done'?'data':'messages';const r=this.svc.queryResult();this.queryHistory.update(items=>[{time:new Date().toLocaleTimeString(),sql,result:r?`${r.command} · ${r.rowCount} rows · ${r.durationMs}ms`:this.svc.queryError()},...items].slice(0,25))}
  async runExplain(){if(!/^explain\b/i.test(this.querySql.trim()))this.querySql=`EXPLAIN ${this.querySql.trim()}`;await this.runQuery()}
  clearQuery(){this.querySql='';this.svc.queryResult.set(null);this.svc.queryError.set('');this.svc.queryState.set('idle')}
  queryMessage(){const result=this.svc.queryResult();if(this.svc.queryState()==='running')return'Executing query…';if(this.svc.queryState()==='error')return this.svc.queryError();if(result)return`${result.command} completed: ${result.rowCount} rows in ${result.durationMs}ms${result.truncated?' (truncated at 500 rows)':''}`;return'No messages.'}
  openCreate(){this.action='create-table';this.draftSchema=this.svc.selectedSchema()||'public';this.draftName='';this.reason='';this.manageOpen=true}
  openManage(){const object=this.svc.selectedObject();if(!object)return;if(object.kind!=='table'&&object.kind!=='partitioned table'){this.openDrop();return}this.action='create-index';this.draftSchema=object.schema;this.draftTable=object.name;this.draftName='';this.reason='';this.manageOpen=true}
  canDropSelected(){return ['table','partitioned table','view','materialized view','sequence','foreign table'].includes(this.svc.selectedObject()?.kind||'')}
  openDrop(){const object=this.svc.selectedObject();if(!object)return;const actions:Record<string,ActionId>={'table':'drop-table','partitioned table':'drop-table','view':'drop-view','materialized view':'drop-materialized-view','sequence':'drop-sequence','foreign table':'drop-foreign-table'};const action=actions[object.kind];if(!action)return;this.action=action;this.draftSchema=object.schema;this.draftName=object.name;this.reason='';this.manageOpen=true}
  actionTitle(){return this.action.split('-').map(x=>x[0].toUpperCase()+x.slice(1)).join(' ')}
  addColumn(){this.draftColumns.update(items=>[...items,{name:'',type:'text',nullable:true,default:''}])}
  removeColumn(index:number){this.draftColumns.update(items=>items.filter((_,i)=>i!==index))}
  actionReady(){if(this.reason.trim().length<8||!this.draftSchema.trim())return false;if(this.action==='create-schema'||this.action==='drop-schema')return true;if(!this.draftName.trim())return false;if(this.action==='create-table')return this.draftColumns().every(c=>c.name.trim()&&c.type);if(this.action==='create-index')return!!this.draftTable.trim()&&!!this.draftIndexColumns.trim();return true}
  sqlPreview(){const s=this.draftSchema||'public',n=this.draftName||'<name>';if(this.action==='create-schema')return`CREATE SCHEMA "${s}"`;if(this.action==='drop-schema')return`DROP SCHEMA "${s}" RESTRICT`;if(this.action==='drop-table')return`DROP TABLE "${s}"."${n}" RESTRICT`;if(this.action==='drop-view')return`DROP VIEW "${s}"."${n}" RESTRICT`;if(this.action==='drop-materialized-view')return`DROP MATERIALIZED VIEW "${s}"."${n}" RESTRICT`;if(this.action==='drop-sequence')return`DROP SEQUENCE "${s}"."${n}" RESTRICT`;if(this.action==='drop-foreign-table')return`DROP FOREIGN TABLE "${s}"."${n}" RESTRICT`;if(this.action==='drop-index')return`DROP INDEX "${s}"."${n}" RESTRICT`;if(this.action==='create-index')return`CREATE${this.draftUnique?' UNIQUE':''} INDEX "${n}" ON "${s}"."${this.draftTable||'<table>'}" (${this.draftIndexColumns||'<columns>'})`;return`CREATE TABLE "${s}"."${n}" (${this.draftColumns().map(c=>`"${c.name||'<column>'}" ${c.type}${c.nullable?'':' NOT NULL'}${c.default?' DEFAULT '+c.default:''}`).join(', ')})`}
  async runAction(){const payload:PgTypedAction={action:this.action,database:this.svc.selectedDatabase(),schema:this.draftSchema.trim(),name:this.draftName.trim()||undefined,table:this.draftTable.trim()||undefined,reason:this.reason.trim(),unique:this.draftUnique,columns:this.action==='create-table'?this.draftColumns().map(c=>({...c,name:c.name.trim()})):undefined,indexColumns:this.action==='create-index'?this.draftIndexColumns.split(',').map(x=>x.trim()).filter(Boolean):undefined};if(await this.svc.execute(payload)){this.manageOpen=false;this.reason=''}}
}
